use super::{
  header_ops::*,
  http_log::HttpMessageLog,
  http_result::{HttpError, HttpResult},
  request_ops::InspectParseHost,
  synthetic_response::{secure_redirection_response, synthetic_error_response, synthetic_error_response_with_close},
};
#[cfg(feature = "sticky-cookie")]
use crate::backend::LoadBalanceContext;
#[cfg(feature = "sticky-cookie")]
use crate::backend::StickyCookieConfig;
use crate::{
  backend::BackendAppManager,
  error::*,
  forwarder::{ForwardRequest, Forwarder},
  globals::Globals,
  hyper_ext::body::{RequestBody, ResponseBody},
  log::*,
  name_exp::ServerName,
};
use derive_builder::Builder;
use http::{Request, Response, StatusCode};
use hyper_util::{client::legacy::connect::Connect, rt::TokioIo};
use std::{net::SocketAddr, sync::Arc};
use tokio::io::copy_bidirectional;

#[derive(Debug)]
/// Context object to handle sticky cookies at HTTP message handler
pub(super) struct HandlerContext {
  #[cfg(feature = "sticky-cookie")]
  pub(super) context_lb: Option<LoadBalanceContext>,
  /// Client-visible request scheme captured from the inbound side (before
  /// `add_forwarding_header()` overwrites X-Forwarded-Proto). True when the request
  /// reached rpxy over TLS, or via a trusted forwarding proxy that asserted HTTPS.
  /// Drives the `Secure` attribute on the sticky-cookie Set-Cookie response.
  #[cfg(feature = "sticky-cookie")]
  pub(super) sticky_cookie_secure: bool,
  #[cfg(feature = "sticky-cookie")]
  pub(super) sticky_cookie_config: Option<StickyCookieConfig>,
}

#[derive(Clone, Builder)]
/// HTTP message handler for requests from clients and responses from backend applications,
/// responsible to manipulate and forward messages to upstream backends and downstream clients.
pub struct HttpMessageHandler<C>
where
  C: Send + Sync + Connect + Clone + 'static,
{
  forwarder: Arc<Forwarder<C>>,
  pub(super) globals: Arc<Globals>,
  app_manager: Arc<BackendAppManager>,
}

impl<C> HttpMessageHandler<C>
where
  C: Send + Sync + Connect + Clone + 'static,
{
  /// Handle incoming request message from a client.
  /// Responsible to passthrough responses from backend applications or generate synthetic error responses.
  pub async fn handle_request(
    &self,
    req: Request<RequestBody>,
    client_addr: SocketAddr, // For access control
    listen_addr: SocketAddr,
    tls_enabled: bool,
    tls_server_name: Option<ServerName>,
  ) -> RpxyResult<Response<ResponseBody>> {
    // Prepare log data only when the installed logger can actually emit an
    // access-log line; otherwise skip the field captures/clones entirely.
    let mut log_data = self
      .globals
      .access_log_enabled
      .then(|| HttpMessageLog::new(&req, self.globals.proxy_config.redact_query_in_access_log));
    if let Some(l) = log_data.as_mut() {
      l.client_addr(&client_addr);
    }

    // Capture before `req` is moved into the inner handler; needed by
    // `synthetic_error_response_with_close` on the PayloadTooLarge path (h1.x must close
    // the connection so the unread body bytes don't get fed into a recycled connection).
    let request_version = req.version();

    let http_result = self
      .handle_request_inner(&mut log_data, req, client_addr, listen_addr, tls_enabled, tls_server_name)
      .await;

    // passthrough or synthetic response
    match http_result {
      Ok(v) => {
        if let Some(l) = log_data.as_mut() {
          l.status_code(&v.status()).output();
        }
        Ok(v)
      }
      Err(e) => {
        // The request summary exists only while the access log is enabled;
        // quiet configurations keep the error and the client address.
        match log_data.as_mut() {
          Some(l) => error!("{e}: {l}"),
          None => error!("{e}: client={client_addr}"),
        }
        let close_connection = matches!(e, HttpError::PayloadTooLarge);
        let code = StatusCode::from(e);
        if let Some(l) = log_data.as_mut() {
          l.status_code(&code).output();
        }
        if close_connection {
          synthetic_error_response_with_close(code, request_version)
        } else {
          synthetic_error_response(code)
        }
      }
    }
  }

  /// Handle inner with no synthetic error response.
  /// Synthetic response is generated by caller.
  async fn handle_request_inner(
    &self,
    log_data: &mut Option<HttpMessageLog>,
    mut req: Request<RequestBody>,
    client_addr: SocketAddr, // For access control
    listen_addr: SocketAddr,
    tls_enabled: bool,
    tls_server_name: Option<ServerName>,
  ) -> HttpResult<Response<ResponseBody>> {
    // Here we start to inspect and parse with server_name. The parsed host is moved into the
    // owning `From<Vec<u8>>` conversion (in-place lowercase) rather than re-copied via a slice.
    let server_name = req
      .inspect_parse_host()
      .map(ServerName::from)
      .map_err(|_e| HttpError::InvalidHostInRequestHeader)?;

    // check consistency of between TLS SNI and HOST/Request URI Line.
    if tls_enabled && self.globals.proxy_config.sni_consistency && !sni_matches(&server_name, tls_server_name.as_ref()) {
      return Err(HttpError::SniHostInconsistency);
    }

    // Pre-flight Content-Length check: reject oversize requests with 413 before any
    // upstream contact. Placed AFTER host inspection and SNI consistency so that
    // malformed-host (400) / SNI-mismatch (421) requests get their specific status codes
    // even when they also carry an oversize Content-Length. The streaming-overrun case
    // is enforced separately at the body adapter (HTTP/1.x and HTTP/2 via the
    // `LimitedIncoming` wrapper, HTTP/3 via its dedicated body-forwarding task) and
    // surfaces as a body error rather than a clean 413.
    check_content_length_limit(&req, self.globals.proxy_config.request_max_body_size)?;
    // Find backend application for given server_name, and drop if incoming request is invalid as request.
    // `default_app` fallback is plaintext-HTTP only (see README and backend_main.rs). TLS requests
    // with an unknown host are rejected regardless of `sni_consistency`.
    let mut fallback_to_default_app = false;
    let backend_app = match self.app_manager.apps.get(&server_name) {
      Some(backend_app) => backend_app,
      None if !tls_enabled => {
        let default_server_name = self
          .app_manager
          .default_server_name
          .as_ref()
          .ok_or(HttpError::NoMatchingBackendApp)?;
        debug!("Serving by default app");
        fallback_to_default_app = true;
        self.app_manager.apps.get(default_server_name).unwrap()
      }
      None => return Err(HttpError::NoMatchingBackendApp),
    };

    // Redirect to https if !tls_enabled and redirect_to_https is true
    if !tls_enabled && backend_app.https_redirection.unwrap_or(false) {
      debug!("Redirect to secure connection: {}", backend_app.server_name);
      return secure_redirection_response(&backend_app.server_name, self.globals.proxy_config.public_https_port, &req);
    }

    // Client authentication (mTLS) is enforced per-vhost during a TLS handshake. After
    // the plaintext redirect opportunity above, an mTLS-protected destination therefore
    // requires a TLS session whose SNI matches the resolved Host. Plaintext, foreign-SNI,
    // and missing-SNI requests have not passed this vhost's client authentication and must
    // fail closed before path lookup or any upstream contact. The ordinary consistency
    // check above still takes precedence whenever the relaxation is disabled.
    check_mutual_tls_session(tls_enabled, backend_app.mutual_tls, &server_name, tls_server_name.as_ref())?;

    // Find reverse proxy for given path and choose one of upstream host
    // Longest prefix match
    let path = req.uri().path();
    let upstream_candidates = backend_app.path_manager.get(path).ok_or(HttpError::NoUpstreamCandidates)?;

    // Upgrade in request header
    let upgrade_in_request = extract_upgrade(req.headers());
    if upgrade_in_request.is_some() && req.version() != http::Version::HTTP_11 {
      return Err(HttpError::FailedToUpgrade(format!(
        "Unsupported HTTP version: {:?}",
        req.version()
      )));
    }
    // let request_upgraded = req.extensions_mut().remove::<hyper::upgrade::OnUpgrade>();
    let req_on_upgrade = hyper::upgrade::on(&mut req);

    // If this request was matched via the `default_app` fallback, the incoming `Host` is untrusted.
    // Pass the matched backend's configured server_name through without allocating so that
    // `generate_request_forwarded` can force-overwrite `Host` after the usual header pass.
    let fallback_host = fallback_to_default_app.then_some(&backend_app.server_name);

    // Build request from destination information
    let _context = self
      .generate_request_forwarded(
        &client_addr,
        &listen_addr,
        &mut req,
        &upgrade_in_request,
        upstream_candidates,
        tls_enabled,
        fallback_host,
      )
      .map_err(|e| HttpError::FailedToGenerateUpstreamRequest(e.to_string()))?;

    debug!(
      "Request to be forwarded: [uri {}, method: {}, version {:?}, headers {:?}]",
      req.uri(),
      req.method(),
      req.version(),
      DebugHeaders::new(req.headers(), self.globals.unsafe_debug_headers)
    );
    if let Some(l) = log_data.as_mut() {
      l.xff(&req.headers().get(header_defs::X_FORWARDED_FOR));
      l.upstream(req.uri());
    }
    //////

    //////////////
    // Forward request to a chosen backend
    let mut res_backend = self
      .forwarder
      .request(req)
      .await
      .map_err(|e| HttpError::FailedToGetResponseFromBackend(e.to_string()))?;

    //////////////
    // Process reverse proxy context generated during the forwarding request generation.
    #[cfg(feature = "sticky-cookie")]
    if let Some(context_from_lb) = _context.context_lb {
      let sticky_config = _context
        .sticky_cookie_config
        .as_ref()
        .ok_or_else(|| HttpError::FailedToAddSetCookeInResponse("missing sticky-cookie config".to_string()))?;
      let cipher = self
        .globals
        .sticky_cookie_cipher
        .as_deref()
        .ok_or_else(|| HttpError::FailedToAddSetCookeInResponse("missing sticky-cookie cipher".to_string()))?;
      let res_headers = res_backend.headers_mut();
      if let Err(e) = set_sticky_cookie_lb_context(
        res_headers,
        &context_from_lb,
        sticky_config,
        _context.sticky_cookie_secure,
        cipher,
      ) {
        return Err(HttpError::FailedToAddSetCookeInResponse(e.to_string()));
      }
    }

    if res_backend.status() != StatusCode::SWITCHING_PROTOCOLS {
      // Generate response to client
      self
        .generate_response_forwarded(&mut res_backend, backend_app, tls_enabled)
        .map_err(|e| HttpError::FailedToGenerateDownstreamResponse(e.to_string()))?;
      return Ok(res_backend);
    }

    // Handle StatusCode::SWITCHING_PROTOCOLS in response
    let upgrade_in_response = extract_upgrade(res_backend.headers());
    let should_upgrade = match (upgrade_in_request.as_ref(), upgrade_in_response.as_ref()) {
      (Some(u_req), Some(u_res)) => u_req.eq_ignore_ascii_case(u_res),
      _ => false,
    };

    if !should_upgrade {
      return Err(HttpError::FailedToUpgrade(format!(
        "Backend tried to switch to protocol {:?} when {:?} was requested",
        upgrade_in_response, upgrade_in_request
      )));
    }
    // let Some(request_upgraded) = request_upgraded else {
    //   return Err(HttpError::NoUpgradeExtensionInRequest);
    // };

    // let Some(onupgrade) = res_backend.extensions_mut().remove::<hyper::upgrade::OnUpgrade>() else {
    //   return Err(HttpError::NoUpgradeExtensionInResponse);
    // };
    let res_on_upgrade = hyper::upgrade::on(&mut res_backend);

    self.globals.runtime_handle.spawn(async move {
      let mut response_upgraded = TokioIo::new(res_on_upgrade.await.map_err(|e| {
        error!("Failed to upgrade response: {}", e);
        RpxyError::FailedToUpgradeResponse(e.to_string())
      })?);
      let mut request_upgraded = TokioIo::new(req_on_upgrade.await.map_err(|e| {
        error!("Failed to upgrade request: {}", e);
        RpxyError::FailedToUpgradeRequest(e.to_string())
      })?);
      copy_bidirectional(&mut response_upgraded, &mut request_upgraded)
        .await
        .map_err(|e| {
          error!("Coping between upgraded connections failed: {}", e);
          RpxyError::FailedToCopyBidirectional(e.to_string())
        })?;
      Ok(()) as RpxyResult<()>
    });

    Ok(res_backend)
  }
}

/// Pre-flight `Content-Length` check.
///
/// Returns `Err(HttpError::PayloadTooLarge)` only when the inbound request advertises a
/// `Content-Length` that exceeds the configured `limit` (i.e. an oversize upload we can
/// detect *before* contacting the upstream). Returns `Ok(())` when the limit is `None`
/// (unlimited), when the header is absent or malformed (chunked / streamed bodies are
/// caught later by the body adapter), or when the announced length is within the limit.
fn check_content_length_limit<B>(req: &Request<B>, limit: Option<usize>) -> HttpResult<()> {
  let Some(limit) = limit else {
    return Ok(());
  };
  let Some(value) = req.headers().get(http::header::CONTENT_LENGTH) else {
    return Ok(());
  };
  // Malformed Content-Length: let the downstream parser (hyper) handle it; we are only
  // responsible for the size-bound check here. Parse as `u64` so that a syntactically
  // valid but very large value (e.g. > 4 GiB on a 32-bit target) does not silently fall
  // out of `s.parse::<usize>()` and skip the pre-flight 413; the comparison is widened
  // to `u64`.
  let Ok(s) = value.to_str() else { return Ok(()) };
  let Ok(n) = s.parse::<u64>() else { return Ok(()) };
  if n > limit as u64 {
    return Err(HttpError::PayloadTooLarge);
  }
  Ok(())
}

/// SNI == Host comparison shared by the early consistency check and the mTLS guard in
/// `handle_request_inner`. `None` (no SNI available on the session) never matches
/// (fail-closed).
fn sni_matches(server_name: &ServerName, tls_server_name: Option<&ServerName>) -> bool {
  tls_server_name == Some(server_name)
}

/// Require a valid matching TLS session for an mTLS-protected destination.
///
/// Client authentication is enforced per-vhost at TLS-handshake time by the `ServerConfig`
/// selected via SNI, so an mTLS-required vhost (`backend_mutual_tls == Some(true)`) can
/// only accept a request carried by TLS with SNI equal to the resolved Host. Plaintext,
/// foreign-SNI, and missing-SNI requests are rejected regardless of the `sni_consistency`
/// setting. Vhosts without client auth (`Some(false)`) and apps without a TLS config
/// (`None`) are unaffected.
fn check_mutual_tls_session(
  tls_enabled: bool,
  backend_mutual_tls: Option<bool>,
  server_name: &ServerName,
  tls_server_name: Option<&ServerName>,
) -> HttpResult<()> {
  if backend_mutual_tls == Some(true) && (!tls_enabled || !sni_matches(server_name, tls_server_name)) {
    return Err(HttpError::MutualTlsHostInconsistency);
  }
  Ok(())
}

#[cfg(test)]
mod tests {
  use super::*;

  fn req_with_cl(value: &str) -> Request<()> {
    let mut req = Request::new(());
    req.headers_mut().insert(http::header::CONTENT_LENGTH, value.parse().unwrap());
    req
  }

  /// CL strictly above the limit -> 413.
  #[test]
  fn check_content_length_limit_rejects_oversize() {
    let req = req_with_cl("100");
    let err = check_content_length_limit(&req, Some(50)).unwrap_err();
    assert!(matches!(err, HttpError::PayloadTooLarge));
  }

  /// CL equal to the limit -> allow (boundary).
  #[test]
  fn check_content_length_limit_allows_equal_to_limit() {
    let req = req_with_cl("50");
    assert!(check_content_length_limit(&req, Some(50)).is_ok());
  }

  /// CL below the limit -> allow.
  #[test]
  fn check_content_length_limit_allows_under_limit() {
    let req = req_with_cl("10");
    assert!(check_content_length_limit(&req, Some(50)).is_ok());
  }

  /// Header absent (chunked / streamed) -> defer to the streaming body adapter; ok here.
  #[test]
  fn check_content_length_limit_passes_when_header_absent() {
    let req: Request<()> = Request::new(());
    assert!(check_content_length_limit(&req, Some(50)).is_ok());
  }

  /// Malformed CL value -> ok (let hyper handle the bad-request rejection downstream).
  #[test]
  fn check_content_length_limit_passes_on_malformed_header() {
    let req = req_with_cl("not-a-number");
    assert!(check_content_length_limit(&req, Some(50)).is_ok());
  }

  /// `None` limit -> unlimited; no rejection regardless of CL value.
  #[test]
  fn check_content_length_limit_unlimited_when_none() {
    let req = req_with_cl("999999999");
    assert!(check_content_length_limit(&req, None).is_ok());
  }

  /// `Some(0)` semantics: only the zero-length body passes. The top-level config
  /// maps `0` to `None` (unlimited), but programmatic callers may still supply
  /// `Some(0)`; this helper preserves the generic `Option<usize>` contract.
  #[test]
  fn check_content_length_limit_zero_rejects_non_empty() {
    let req = req_with_cl("1");
    assert!(matches!(
      check_content_length_limit(&req, Some(0)).unwrap_err(),
      HttpError::PayloadTooLarge
    ));
    let req = req_with_cl("0");
    assert!(check_content_length_limit(&req, Some(0)).is_ok());
  }

  /// Regression: an oversize CL whose numeric value would overflow `usize` on a 32-bit
  /// target (and `u64::MAX` even on 64-bit) must still be rejected as PayloadTooLarge.
  /// Parsing as `u64` and comparing against `limit as u64` is what guarantees this; a
  /// previous `s.parse::<usize>()` would have failed on 32-bit and silently skipped the
  /// pre-flight 413.
  #[test]
  fn check_content_length_limit_rejects_value_overflowing_usize() {
    // Larger than usize::MAX on a 32-bit target (4_294_967_295) and larger than any
    // realistic `request_max_body_size`; still well within u64 (u64::MAX ~= 1.8e19).
    let req = req_with_cl("9999999999999");
    let err = check_content_length_limit(&req, Some(256 * 1024 * 1024)).unwrap_err();
    assert!(matches!(err, HttpError::PayloadTooLarge));
    // u64::MAX as a header value is still rejected (the largest value that parses).
    let req = req_with_cl(&u64::MAX.to_string());
    let err = check_content_length_limit(&req, Some(256 * 1024 * 1024)).unwrap_err();
    assert!(matches!(err, HttpError::PayloadTooLarge));
    // A value that does not even fit in `u64` is treated as malformed and deferred to
    // the streaming body adapter (consistent with the existing malformed-header test).
    let req = req_with_cl("99999999999999999999999999");
    assert!(check_content_length_limit(&req, Some(256 * 1024 * 1024)).is_ok());
  }

  // --- mTLS SNI-consistency guard (helper level) ---

  fn sn(host: &str) -> ServerName {
    ServerName::from(host)
  }

  /// mTLS vhost + SNI == Host -> allowed (input representing a valid mTLS session; the
  /// helper itself performs no handshake).
  #[test]
  fn mtls_guard_allows_matching_sni() {
    let host = sn("mtls.example.com");
    assert!(check_mutual_tls_session(true, Some(true), &host, Some(&host)).is_ok());
  }

  /// mTLS vhost + SNI != Host -> rejected: the session's handshake belonged to another
  /// vhost, so the resolved vhost's client authentication never happened (the bypass the
  /// relaxation would otherwise open).
  #[test]
  fn mtls_guard_rejects_mismatching_sni() {
    let err = check_mutual_tls_session(true, Some(true), &sn("mtls.example.com"), Some(&sn("plain.example.com"))).unwrap_err();
    assert!(matches!(err, HttpError::MutualTlsHostInconsistency));
  }

  /// mTLS vhost + no SNI on the session -> rejected (fail-closed).
  #[test]
  fn mtls_guard_rejects_missing_sni() {
    let err = check_mutual_tls_session(true, Some(true), &sn("mtls.example.com"), None).unwrap_err();
    assert!(matches!(err, HttpError::MutualTlsHostInconsistency));
  }

  /// TLS vhost WITHOUT client auth + mismatch -> allowed: the relaxation keeps working
  /// for its documented purpose.
  #[test]
  fn mtls_guard_ignores_non_mtls_tls_vhost() {
    assert!(check_mutual_tls_session(true, Some(false), &sn("a.example.com"), Some(&sn("b.example.com"))).is_ok());
  }

  /// Target app without any TLS config (`None`) + mismatch -> allowed.
  #[test]
  fn mtls_guard_ignores_app_without_tls_config() {
    assert!(check_mutual_tls_session(true, None, &sn("a.example.com"), Some(&sn("b.example.com"))).is_ok());
  }

  /// Plaintext request to an mTLS vhost after the redirect opportunity -> rejected because
  /// no client-certificate authentication occurred.
  #[test]
  fn mtls_guard_rejects_plaintext() {
    let err = check_mutual_tls_session(false, Some(true), &sn("mtls.example.com"), None).unwrap_err();
    assert!(matches!(err, HttpError::MutualTlsHostInconsistency));
  }

  /// Plaintext request to a non-mTLS vhost remains outside the guard.
  #[test]
  fn mtls_guard_allows_plaintext_for_non_mtls_vhost() {
    assert!(check_mutual_tls_session(false, Some(false), &sn("plain.example.com"), None).is_ok());
  }

  /// `sni_matches` triple pinning the borrowing rewrite of the early consistency check:
  /// match / mismatch / no-SNI (never matches, fail-closed).
  #[test]
  fn sni_matches_match_mismatch_and_none() {
    let host = sn("example.com");
    assert!(sni_matches(&host, Some(&sn("example.com"))));
    assert!(!sni_matches(&host, Some(&sn("other.example.com"))));
    assert!(!sni_matches(&host, None));
  }

  // --- mTLS SNI-consistency guard (handler-path wiring; design D2b, tests 9-11) ---

  use crate::backend::BackendApp;
  use crate::{
    globals::{AppConfig, ProxyConfig, ReverseProxyConfig, TlsConfig, UpstreamUri},
    hyper_ext::body::IncomingLike,
  };

  /// Globals for handler-instance tests. `sni_consistency = false` models the operator
  /// relaxation (`experimental.ignore_sni_consistency = true`).
  ///
  /// Installing the default CryptoProvider mirrors the production entrypoint (lib.rs),
  /// which does so before building the forwarder; without it the rustls-backend
  /// `Forwarder::try_new` panics on the missing process-level provider (idempotent,
  /// same pattern as the rpxy-certs tests).
  fn test_globals(sni_consistency: bool) -> Arc<Globals> {
    let _ = rustls::crypto::CryptoProvider::install_default(rustls::crypto::aws_lc_rs::default_provider());
    let proxy_config = ProxyConfig {
      sni_consistency,
      ..ProxyConfig::default()
    };
    Arc::new(Globals {
      proxy_config,
      runtime_handle: tokio::runtime::Handle::current(),
      cert_reloader_rx: None,
      unsafe_debug_headers: false,
      access_log_enabled: false,
      #[cfg(feature = "sticky-cookie")]
      sticky_cookie_cipher: None,
      #[cfg(feature = "acme")]
      server_configs_acme_challenge: Default::default(),
    })
  }

  /// One TLS-configured app routing to `upstream`.
  fn test_app_config(server_name: &str, mutual_tls: bool, https_redirection: bool, upstream: &str) -> AppConfig {
    AppConfig {
      app_name: server_name.to_string(),
      server_name: server_name.to_string(),
      reverse_proxy: vec![ReverseProxyConfig {
        path: None,
        replace_path: None,
        upstream: vec![UpstreamUri {
          inner: upstream.parse().unwrap(),
        }],
        upstream_options: None,
        load_balance: None,
        #[cfg(feature = "health-check")]
        health_check: None,
      }],
      tls: Some(TlsConfig {
        mutual_tls,
        https_redirection,
        #[cfg(feature = "acme")]
        acme: false,
      }),
    }
  }

  /// `plain.example.com` (TLS, no client auth) + `mtls.example.com` (client auth), both
  /// routing to `upstream`.
  fn test_app_manager(upstream: &str) -> Arc<BackendAppManager> {
    let mut manager = BackendAppManager::default();
    for (name, mutual_tls) in [("plain.example.com", false), ("mtls.example.com", true)] {
      let config = test_app_config(name, mutual_tls, true, upstream);
      let app = BackendApp::try_from(&config).unwrap();
      manager.apps.insert(sn(name), app);
    }
    Arc::new(manager)
  }

  /// One app with independently selectable client authentication, HTTPS redirection,
  /// and plaintext `default_app` fallback behavior.
  fn single_test_app_manager(
    server_name: &str,
    mutual_tls: bool,
    https_redirection: bool,
    upstream: &str,
    default_app: bool,
  ) -> Arc<BackendAppManager> {
    let config = test_app_config(server_name, mutual_tls, https_redirection, upstream);
    let app = BackendApp::try_from(&config).unwrap();
    let server_name = sn(server_name);
    let mut manager = BackendAppManager::default();
    manager.apps.insert(server_name.clone(), app);
    if default_app {
      manager.default_server_name = Some(server_name);
    }
    Arc::new(manager)
  }

  /// Counting upstream stand-in with a minimal HTTP/1.1 responder.
  async fn counting_upstream() -> (String, Arc<std::sync::atomic::AtomicUsize>, tokio::task::JoinHandle<()>) {
    use std::sync::atomic::{AtomicUsize, Ordering};
    use tokio::io::{AsyncReadExt, AsyncWriteExt};

    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let upstream = format!("http://{}/", listener.local_addr().unwrap());
    let accepted = Arc::new(AtomicUsize::new(0));
    let accepted_in_task = accepted.clone();
    let accept_task = tokio::spawn(async move {
      loop {
        let Ok((mut stream, _)) = listener.accept().await else { break };
        accepted_in_task.fetch_add(1, Ordering::SeqCst);
        tokio::spawn(async move {
          let mut buf = [0u8; 1024];
          let bytes_read = stream.read(&mut buf).await.unwrap();
          assert!(bytes_read > 0, "the upstream received an empty request");
          stream
            .write_all(b"HTTP/1.1 200 OK\r\ncontent-length: 0\r\n\r\n")
            .await
            .unwrap();
        });
      }
    });
    (upstream, accepted, accept_task)
  }

  /// A GET request carrying `authority` as its host, with an inert streaming body.
  fn test_request(authority: &str) -> Request<RequestBody> {
    let (_tx, body) = IncomingLike::channel();
    Request::builder()
      .method("GET")
      .uri(format!("https://{authority}/"))
      .body(RequestBody::IncomingLike(body))
      .unwrap()
  }

  /// Plaintext to an mTLS app retains the existing HTTPS redirect and never contacts
  /// the upstream.
  #[tokio::test]
  async fn handler_redirects_plaintext_mtls_without_upstream_contact() {
    use std::sync::atomic::Ordering;

    let (upstream, accepted, accept_task) = counting_upstream().await;
    let globals = test_globals(false);
    let forwarder = Arc::new(Forwarder::try_new(&globals).await.unwrap());
    let handler = HttpMessageHandler {
      forwarder,
      globals,
      app_manager: single_test_app_manager("mtls.example.com", true, true, &upstream, false),
    };

    let response = handler
      .handle_request_inner(
        &mut None,
        test_request("mtls.example.com"),
        "192.0.2.1:12345".parse().unwrap(),
        "127.0.0.1:8080".parse().unwrap(),
        false,
        None,
      )
      .await
      .unwrap();
    assert_eq!(response.status(), StatusCode::MOVED_PERMANENTLY);
    assert_eq!(accepted.load(Ordering::SeqCst), 0, "a redirect must not contact the upstream");

    accept_task.abort();
  }

  /// Plaintext to an mTLS app with redirection disabled fails closed with 421 before
  /// upstream contact.
  #[tokio::test]
  async fn handler_rejects_plaintext_mtls_without_upstream_contact() {
    use std::sync::atomic::Ordering;

    let (upstream, accepted, accept_task) = counting_upstream().await;
    let globals = test_globals(false);
    let forwarder = Arc::new(Forwarder::try_new(&globals).await.unwrap());
    let handler = HttpMessageHandler {
      forwarder,
      globals,
      app_manager: single_test_app_manager("mtls.example.com", true, false, &upstream, false),
    };

    let result = handler
      .handle_request_inner(
        &mut None,
        test_request("mtls.example.com"),
        "192.0.2.1:12345".parse().unwrap(),
        "127.0.0.1:8080".parse().unwrap(),
        false,
        None,
      )
      .await;
    let Err(err) = result else {
      panic!("plaintext to an mTLS app with redirection disabled must be rejected");
    };
    assert!(matches!(err, HttpError::MutualTlsHostInconsistency));
    let code: StatusCode = err.into();
    assert_eq!(code.as_u16(), 421);
    assert_eq!(
      accepted.load(Ordering::SeqCst),
      0,
      "a rejected request must not contact the upstream"
    );

    accept_task.abort();
  }

  /// Plaintext to a non-mTLS app with redirection disabled remains forwardable. This is
  /// the positive control proving that the counting upstream observes contact.
  #[tokio::test]
  async fn handler_forwards_plaintext_non_mtls_when_redirection_is_disabled() {
    use std::sync::atomic::Ordering;

    let (upstream, accepted, accept_task) = counting_upstream().await;
    let globals = test_globals(false);
    let forwarder = Arc::new(Forwarder::try_new(&globals).await.unwrap());
    let handler = HttpMessageHandler {
      forwarder,
      globals,
      app_manager: single_test_app_manager("plain.example.com", false, false, &upstream, false),
    };

    let response = handler
      .handle_request_inner(
        &mut None,
        test_request("plain.example.com"),
        "192.0.2.1:12345".parse().unwrap(),
        "127.0.0.1:8080".parse().unwrap(),
        false,
        None,
      )
      .await
      .unwrap();
    assert_eq!(response.status(), StatusCode::OK);
    assert_eq!(
      accepted.load(Ordering::SeqCst),
      1,
      "the positive control must contact the upstream"
    );

    accept_task.abort();
  }

  /// Plaintext `default_app` fallback uses the resolved app's mTLS policy, so an unknown
  /// Host is rejected with 421 before upstream contact when redirection is disabled.
  #[tokio::test]
  async fn handler_rejects_plaintext_mtls_default_app_without_upstream_contact() {
    use std::sync::atomic::Ordering;

    let (upstream, accepted, accept_task) = counting_upstream().await;
    let globals = test_globals(false);
    let forwarder = Arc::new(Forwarder::try_new(&globals).await.unwrap());
    let handler = HttpMessageHandler {
      forwarder,
      globals,
      app_manager: single_test_app_manager("mtls.example.com", true, false, &upstream, true),
    };

    let result = handler
      .handle_request_inner(
        &mut None,
        test_request("unknown.example.com"),
        "192.0.2.1:12345".parse().unwrap(),
        "127.0.0.1:8080".parse().unwrap(),
        false,
        None,
      )
      .await;
    let Err(err) = result else {
      panic!("plaintext default-app fallback to an mTLS app must be rejected");
    };
    assert!(matches!(err, HttpError::MutualTlsHostInconsistency));
    let code: StatusCode = err.into();
    assert_eq!(code.as_u16(), 421);
    assert_eq!(
      accepted.load(Ordering::SeqCst),
      0,
      "a rejected fallback must not contact the upstream"
    );

    accept_task.abort();
  }

  /// Pre-flight Content-Length rejection retains precedence over both the plaintext
  /// redirect and the mTLS guard, with zero upstream contact.
  #[tokio::test]
  async fn handler_prefers_413_over_plaintext_mtls_policy() {
    use std::sync::atomic::Ordering;

    let (upstream, accepted, accept_task) = counting_upstream().await;
    let globals = test_globals(false);
    let limit = globals.proxy_config.request_max_body_size.expect("default limit is bounded");
    let forwarder = Arc::new(Forwarder::try_new(&globals).await.unwrap());
    let handler = HttpMessageHandler {
      forwarder,
      globals,
      app_manager: single_test_app_manager("mtls.example.com", true, true, &upstream, false),
    };
    let mut req = test_request("mtls.example.com");
    req
      .headers_mut()
      .insert(http::header::CONTENT_LENGTH, (limit as u64 + 1).to_string().parse().unwrap());

    let result = handler
      .handle_request_inner(
        &mut None,
        req,
        "192.0.2.1:12345".parse().unwrap(),
        "127.0.0.1:8080".parse().unwrap(),
        false,
        None,
      )
      .await;
    let Err(err) = result else {
      panic!("an oversize plaintext request must be rejected before mTLS routing policy");
    };
    assert!(matches!(err, HttpError::PayloadTooLarge));
    let code: StatusCode = err.into();
    assert_eq!(code.as_u16(), 413);
    assert_eq!(
      accepted.load(Ordering::SeqCst),
      0,
      "a pre-flight 413 must not contact the upstream"
    );

    accept_task.abort();
  }

  /// Design test 9 (wiring + direct no-contact proof): with the relaxation enabled, a
  /// request over a TLS session whose SNI belongs to a non-mTLS vhost but whose Host
  /// resolves to an mTLS vhost is rejected by the guard INSIDE `handle_request_inner`
  /// with ZERO upstream contact. Order matters for the proof: the guarded request runs
  /// FIRST, against an empty connection pool — any forwarding would then require a
  /// fresh TCP accept (the counter counts connections, not HTTP requests, so a pooled
  /// connection from an earlier request could mask contact). The positive control runs
  /// AFTER and must bump the counter, proving this setup can observe contact at all.
  #[tokio::test]
  async fn handler_rejects_mtls_host_over_foreign_sni_when_relaxed() {
    use std::sync::atomic::{AtomicUsize, Ordering};
    use tokio::io::{AsyncReadExt, AsyncWriteExt};

    // Counting upstream stand-in with a minimal HTTP/1.1 responder.
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let upstream = format!("http://{}/", listener.local_addr().unwrap());
    let accepted = Arc::new(AtomicUsize::new(0));
    let accepted_in_task = accepted.clone();
    let accept_task = tokio::spawn(async move {
      loop {
        let Ok((mut stream, _)) = listener.accept().await else { break };
        accepted_in_task.fetch_add(1, Ordering::SeqCst);
        tokio::spawn(async move {
          let mut buf = [0u8; 1024];
          let _ = stream.read(&mut buf).await;
          let _ = stream.write_all(b"HTTP/1.1 200 OK\r\ncontent-length: 0\r\n\r\n").await;
        });
      }
    });

    let globals = test_globals(false); // relaxation enabled
    let forwarder = Arc::new(Forwarder::try_new(&globals).await.unwrap());
    let handler = HttpMessageHandler {
      forwarder,
      globals,
      app_manager: test_app_manager(&upstream),
    };

    // The guarded request, first, against an EMPTY pool: exact guard variant AND zero
    // TCP accepts = direct no-contact proof.
    let result = handler
      .handle_request_inner(
        &mut None,
        test_request("mtls.example.com"),
        "192.0.2.1:12345".parse().unwrap(),
        "127.0.0.1:8443".parse().unwrap(),
        true,
        Some(sn("plain.example.com")),
      )
      .await;
    let Err(err) = result else {
      panic!("an mTLS vhost addressed over a foreign-SNI session must be rejected");
    };
    assert!(
      matches!(err, HttpError::MutualTlsHostInconsistency),
      "expected the mTLS guard, got: {err}"
    );
    let code: StatusCode = err.into();
    assert_eq!(code.as_u16(), 421);
    assert_eq!(
      accepted.load(Ordering::SeqCst),
      0,
      "the guarded request must never contact the upstream"
    );

    // Positive control, after: not covered by the guard (non-mTLS vhost, matching SNI)
    // -> forwarded, answered, and observed by the same counter.
    let control = handler
      .handle_request_inner(
        &mut None,
        test_request("plain.example.com"),
        "192.0.2.1:12345".parse().unwrap(),
        "127.0.0.1:8443".parse().unwrap(),
        true,
        Some(sn("plain.example.com")),
      )
      .await;
    assert!(control.is_ok(), "the control request must be forwarded and answered");
    assert_eq!(
      accepted.load(Ordering::SeqCst),
      1,
      "the control request must have contacted the upstream"
    );

    accept_task.abort();
  }

  /// Design test 10 (D3b precedence): when the same relaxed-mode mTLS mismatch also
  /// carries an oversize Content-Length, the pre-flight 413 wins because it runs before
  /// backend resolution; the request still never reaches any upstream.
  #[tokio::test]
  async fn handler_prefers_413_over_mtls_guard_when_both_apply() {
    let globals = test_globals(false); // relaxation enabled
    let limit = globals.proxy_config.request_max_body_size.expect("default limit is bounded");
    let forwarder = Arc::new(Forwarder::try_new(&globals).await.unwrap());
    let handler = HttpMessageHandler {
      forwarder,
      globals,
      app_manager: test_app_manager("http://127.0.0.1:1/"),
    };

    let mut req = test_request("mtls.example.com");
    req
      .headers_mut()
      .insert(http::header::CONTENT_LENGTH, (limit as u64 + 1).to_string().parse().unwrap());
    let result = handler
      .handle_request_inner(
        &mut None,
        req,
        "192.0.2.1:12345".parse().unwrap(),
        "127.0.0.1:8443".parse().unwrap(),
        true,
        Some(sn("plain.example.com")),
      )
      .await;
    let Err(err) = result else {
      panic!("an oversize mismatching request must be rejected");
    };
    assert!(
      matches!(err, HttpError::PayloadTooLarge),
      "the pre-flight 413 precedes the mTLS guard, got: {err}"
    );
    let code: StatusCode = err.into();
    assert_eq!(code.as_u16(), 413);
  }

  /// Design test 11 (default behavior): with the relaxation DISABLED (internal
  /// `sni_consistency = true`, the default), a mismatch is rejected by the EARLY check —
  /// pinning that the borrowing rewrite did not change default-config behavior. Uses the
  /// same REGISTERED name pair as test 9 (a real TLS acceptor refuses unknown SNIs
  /// before the handler, so an unregistered SNI would not model a reachable state); the
  /// early-check variant, not the mTLS-guard variant, must win at default settings.
  #[tokio::test]
  async fn handler_default_flag_rejects_mismatch_via_early_check() {
    let globals = test_globals(true); // default: consistency enforced
    let forwarder = Arc::new(Forwarder::try_new(&globals).await.unwrap());
    let handler = HttpMessageHandler {
      forwarder,
      globals,
      app_manager: test_app_manager("http://127.0.0.1:1/"),
    };

    let result = handler
      .handle_request_inner(
        &mut None,
        test_request("mtls.example.com"),
        "192.0.2.1:12345".parse().unwrap(),
        "127.0.0.1:8443".parse().unwrap(),
        true,
        Some(sn("plain.example.com")),
      )
      .await;
    let Err(err) = result else {
      panic!("a mismatching request must be rejected at default settings");
    };
    assert!(
      matches!(err, HttpError::SniHostInconsistency),
      "expected the early consistency check, got: {err}"
    );
    let code: StatusCode = err.into();
    assert_eq!(code.as_u16(), 421);
  }
}
