#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
    # Remove the rpxy user
    if getent passwd rpxy >/dev/null; then
        deluser --quiet --system rpxy >/dev/null || true
    fi

    # Remove config directory
    rm -rf /etc/rpxy

    # Remove systemd service state
    deb-systemd-helper purge rpxy.service >/dev/null || true
    deb-systemd-helper unmask rpxy.service >/dev/null || true
fi

if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi

exit 0
