version: "3"
services:
  rpxy-rp:
    image: jqtype/rpxy:slim # ghcr.io/junkurihara/rust-rpxy:slim also works
    container_name: rpxy
    init: true
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:8080/tcp
      - 127.0.0.1:8443:8443/udp
      - 127.0.0.1:8443:8443/tcp
    # build: # Uncomment if you build yourself
    #   context: ../
    #   additional_contexts:
    #     - messense/rust-musl-cross:amd64-musl=docker-image://messense/rust-musl-cross:x86_64-musl
    #     - messense/rust-musl-cross:arm64-musl=docker-image://messense/rust-musl-cross:aarch64-musl
    #   dockerfile: ./docker/Dockerfile-slim # based on alpine and build x86_64-unknown-linux-musl
    #   platforms: # Choose your platforms
    #     - "linux/amd64"
    #     # - "linux/arm64"
    environment:
      - LOG_LEVEL=debug
      - LOG_TO_FILE=true
      - HOST_USER=jun
      - HOST_UID=501
      - HOST_GID=501
      # - WATCH=true
    tty: false
    privileged: true
    volumes:
      - ./log:/rpxy/log
      - ../example-certs/server.crt:/certs/server.crt:ro
      - ../example-certs/server.key:/certs/server.key:ro
      - ../config-example.toml:/etc/rpxy.toml:ro
