services:
  nginx:
    image: nginx:alpine
    container_name: backend-nginx
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80
    expose:
      - 80
    # ports:
    # - 127.0.0.1:8888:80
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      bench-nw:
        ipv4_address: 192.168.100.100

  rpxy-rp:
    image: jqtype/rpxy
    container_name: proxy-rpxy
    pull_policy: never
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    environment:
      - LOG_LEVEL=error # almost nolog
      - LOG_TO_FILE=false
    ports:
      - 127.0.0.1:8080:8080
    tty: false
    volumes:
      - ./rpxy.toml:/etc/rpxy.toml:ro
    networks:
      bench-nw:

  nginx-rp:
    image: nginx:alpine
    container_name: proxy-nginx
    ports:
      - 127.0.0.1:8090:80
    restart: unless-stopped
    tty: false
    privileged: true
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # set as almost nolog
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      bench-nw:

  caddy-rp:
    image: caddy:2
    container_name: proxy-caddy
    ports:
      - 127.0.0.1:8100:80
    restart: unless-stopped
    tty: false
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro # set as almost no log
    networks:
      bench-nw:

  # Sozu wokrs only in X86_64 (amd64) environment
  # Official image from sozu developers is still version 0.11.0.
  # So we built it by ourselves locally.
  sozu-rp:
    image: jqtype/sozu
    container_name: proxy-sozu
    restart: unless-stopped
    ports:
      - 127.0.0.1:8110:80
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./sozu-config.toml:/etc/sozu/config.toml # set as almost nolog
    networks:
      bench-nw:

networks:
  bench-nw:
    name: bench-nw
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
