//! Internal representation of the forwarding chain used by rpxy.
//!
//! The flow is:
//! 1. Parse `Forwarded` and/or `X-Forwarded-*` into `ForwardedEntry`
//! 2. Append the immediate peer as rpxy's authoritative latest hop
//! 3. Trim trusted proxy hops from the right-hand side
//! 4. Regenerate outgoing `X-Forwarded-*` / `Forwarded` from the normalized chain
//!
//! Keeping this representation in one place makes the trust-boundary logic
//! easier to audit than passing partially parsed headers across multiple helpers.

use anyhow::{Result, anyhow};
use http::{HeaderMap, HeaderName, HeaderValue, Uri, header, header::AsHeaderName};
use ipnet::IpNet;
use std::{
  net::{IpAddr, SocketAddr},
  str::FromStr,
};

use crate::log::*;

use super::{
  super::canonical_address::ToCanonical,
  common::{add_header_entry_overwrite_if_exist, host_from_uri_or_host_header, make_cookie_single_line},
  header_defs::*,
};

fn overwrite_x_forwarded_host_from_original(
  headers: &mut HeaderMap,
  original_uri: &Uri,
) -> Result<()> {
  match host_from_uri_or_host_header(original_uri, headers.get(header::HOST)) {
    Ok(original_host) => add_header_entry_overwrite_if_exist(headers, X_FORWARDED_HOST, original_host)?,
    Err(_) => {
      headers.remove(X_FORWARDED_HOST);
    }
  }
  Ok(())
}

/* --------------------------------------------------------------------------------------------------------- */
/* Forwarding header normalization model                                                                   */
/* --------------------------------------------------------------------------------------------------------- */

/// An entry in Forwarded header with only the parameters relevant for forwarding chain normalization and consistency check.
#[derive(Clone, Debug, PartialEq, Eq)]
struct ForwardedNode {
  ip: Option<IpAddr>,
  port: Option<String>,
  raw: ForwardedNodeRaw,
}

#[derive(Clone, Debug, PartialEq, Eq)]
enum ForwardedNodeRaw {
  Ip,
  Unknown,
  Obfuscated(String),
}

impl ForwardedNode {
  fn ip_addr(&self) -> Option<IpAddr> {
    self.ip
  }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(super) struct ForwardedEntry {
  /// for=:
  /// For Forwarded Header: this is optional in the RFC, but we require it for each entry to be able to build the forwarding chain. If missing, the entry is considered invalid.
  for_node: ForwardedNode,
  /// proto=, When generated from incoming X-Forwarded-For, this is always None except for the last entry which was generated by the previous hop proxy. This is used for consistency check against X-Forwarded-Proto.
  proto: Option<String>,
  /// host=, When generated from incoming X-Forwarded-For, this is always None
  host: Option<String>,
  /// by=, When generated from incoming X-Forwarded-For, this is always None.
  by: Option<String>,
}

/// Add or update forwarding headers like `x-forwarded-for`.
/// If only `forwarded` header exists, it will update `x-forwarded-for` with the proxy chain.
/// If both `x-forwarded-for` and `forwarded` headers exist, it will update `x-forwarded-for` first and then add `forwarded` header.
/// If the immediate peer is in trusted_forwarded_proxies,
/// it will recursively trust the incoming forwarding headers and append the immediate peer IP to the end of the chain.
/// Otherwise, it will ignore incoming forwarding headers and start a new chain with the immediate peer IP.
pub(in crate::message_handler) fn add_forwarding_header(
  headers: &mut HeaderMap,
  client_addr: &SocketAddr,
  listen_addr: &SocketAddr,
  tls: bool,
  original_uri: &Uri,
  trusted_forwarded_proxies: &[IpNet],
) -> Result<()> {
  let peer_ip = canonicalize_ip(client_addr.to_canonical().ip());
  let has_forwarded = headers.contains_key(header::FORWARDED);
  let normalized_chain = normalize_forwarding_chain(headers, &peer_ip, tls, original_uri, trusted_forwarded_proxies);
  let peer_entry = build_peer_forwarded_entry(headers, peer_ip, tls, original_uri);

  let (normalized_chain, normalized_for_ip_chain) = match forwarded_chain_to_xff(&normalized_chain) {
    Some(ip_chain) => (normalized_chain, ip_chain),
    None => {
      warn!("Normalized forwarding chain contains non-IP hops; falling back to peer-only forwarding view");
      (vec![peer_entry.clone()], vec![peer_ip.to_string()])
    }
  };

  // For X-Real-IP
  let authoritative_client_ip = normalized_chain
    .first()
    .and_then(|entry| entry.for_node.ip_addr())
    .map(|ip| ip.to_string())
    .unwrap_or_else(|| peer_ip.to_string());

  // Update X-Forwarded-For with normalized chain
  overwrite_header_with_csv(headers, X_FORWARDED_FOR, &normalized_for_ip_chain)?;

  // Preserve/update Forwarded only if it was present on input. If callers want to force
  // Forwarded generation, apply_upstream_options_to_header() will regenerate it later.
  if has_forwarded {
    match generate_forwarded_header(&normalized_chain) {
      Ok(forwarded_value) => add_header_entry_overwrite_if_exist(headers, header::FORWARDED, forwarded_value)?,
      Err(e) => warn!("Failed to update existing Forwarded header for consistency: {}", e),
    }
  } else {
    headers.remove(header::FORWARDED);
  }

  // Single line cookie header
  // TODO: This should be only for HTTP/1.1. For 2+, this can be multi-lined.
  make_cookie_single_line(headers)?;

  // Always overwrite these headers with rpxy's authoritative downstream view.
  add_header_entry_overwrite_if_exist(headers, X_FORWARDED_PROTO, if tls { "https" } else { "http" })?;
  add_header_entry_overwrite_if_exist(headers, X_FORWARDED_PORT, listen_addr.port().to_string())?;

  /////////// As Nginx-Proxy
  // x-real-ip
  add_header_entry_overwrite_if_exist(headers, X_REAL_IP, authoritative_client_ip)?;
  // x-forwarded-ssl
  add_header_entry_overwrite_if_exist(headers, X_FORWARDED_SSL, if tls { "on" } else { "off" })?;
  // x-original-uri
  add_header_entry_overwrite_if_exist(headers, X_ORIGINAL_URI, original_uri.to_string())?;
  // x-forwarded-host
  overwrite_x_forwarded_host_from_original(headers, original_uri)?;
  // proxy
  add_header_entry_overwrite_if_exist(headers, PROXY, "")?;

  Ok(())
}

/* --------------------------------------------------------------------------------------------------------- */
/* High-level forwarding flow                                                                              */
/* --------------------------------------------------------------------------------------------------------- */

/// Normalize forwarding chain based on trusted proxies configuration.
fn normalize_forwarding_chain(
  headers: &HeaderMap,
  peer_ip: &IpAddr,
  tls: bool,
  original_uri: &Uri,
  trusted_forwarded_proxies: &[IpNet],
) -> Vec<ForwardedEntry> {
  let peer_entry = build_peer_forwarded_entry(headers, *peer_ip, tls, original_uri);
  if !is_trusted_proxy(peer_ip, trusted_forwarded_proxies) {
    return vec![peer_entry];
  }

  let mut forwarding_chain = match extract_forwarding_chain_from_headers(headers, None) {
    Ok(Some(chain)) if !chain.is_empty() => chain,
    Ok(_) => {
      return vec![peer_entry];
    }
    Err(e) => {
      warn!("Ignoring incoming forwarding headers from trusted proxy due to parse failure: {e}");
      return vec![peer_entry];
    }
  };

  // Append the immediate peer as the last hop in the chain, which is the authoritative view of this proxy.
  forwarding_chain.push(peer_entry.clone());
  let normalized_chain = reduce_trusted_proxy_chain(forwarding_chain, trusted_forwarded_proxies);
  if normalized_chain.is_empty() {
    return vec![peer_entry];
  }
  normalized_chain
}

/// Extract forwarding information chain from Forwarded or X-Forwarded-For/Proto headers.
/// Returns None if neither header is present.
/// If both are present, prefer Forwarded only when it is consistent with the auxiliary X-Forwarded-* view.
pub(super) fn extract_forwarding_chain_from_headers(
  headers: &HeaderMap,
  authoritative_host: Option<String>,
) -> Result<Option<Vec<ForwardedEntry>>> {
  let xff_chain = if headers.contains_key(X_FORWARDED_FOR) {
    Some(parse_x_forwarded_for_header(headers, authoritative_host)?)
  } else {
    None
  };
  let forwarded_chain = if headers.contains_key(header::FORWARDED) {
    match parse_forwarded_header(headers) {
      Ok(chain) => Some(chain),
      Err(e) if xff_chain.is_some() => {
        warn!("Ignoring invalid Forwarded header and falling back to X-Forwarded-For: {e}");
        None
      }
      Err(e) => return Err(e),
    }
  } else {
    None
  };

  match (forwarded_chain, xff_chain) {
    (Some(forwarded), Some(xff)) => {
      if forwarded_is_consistent(&forwarded, &xff) {
        Ok(Some(forwarded))
      } else {
        warn!("Incoming Forwarded header is inconsistent with X-Forwarded-* headers; falling back to X-Forwarded-For");
        Ok(Some(xff))
      }
    }
    (Some(forwarded), None) => Ok(Some(forwarded)),
    (None, Some(xff)) => Ok(Some(xff)),
    (None, None) => Ok(None),
  }
}

/// Use the trusted suffix at the end of the chain to locate the trust boundary.
/// This keeps the last non-trusted hop together with the trusted suffix after it,
/// and discards any earlier prefix to the left of that boundary.
/// We assume the immediate peer is always appended as the last hop.
pub(super) fn reduce_trusted_proxy_chain(
  mut chain: Vec<ForwardedEntry>,
  trusted_forwarded_proxies: &[IpNet],
) -> Vec<ForwardedEntry> {
  let mut idx = chain.len();
  while idx > 0 && entry_is_trusted_proxy(&chain[idx - 1], trusted_forwarded_proxies) {
    idx -= 1;
  }

  if idx == 0 {
    return chain;
  }
  let authoritative_idx = idx - 1;
  chain.drain(0..authoritative_idx);
  chain
}

/* --------------------------------------------------------------------------------------------------------- */
/* Incoming header parsing                                                                                 */
/* --------------------------------------------------------------------------------------------------------- */

/// Extract IP addresses from X-Forwarded-For header
fn parse_x_forwarded_for_header(headers: &HeaderMap, authoritative_host: Option<String>) -> Result<Vec<ForwardedEntry>> {
  let xff = join_header_values(headers, X_FORWARDED_FOR)?.ok_or_else(|| anyhow!("x-forwarded-for header missing"))?;
  let xf_proto = first_header_value(headers, X_FORWARDED_PROTO)?.map(|s| s.trim().to_string());
  let ips: Vec<&str> = xff.split(',').map(str::trim).filter(|s| !s.is_empty()).collect();
  let last_idx = ips.len().saturating_sub(1);
  let mut chain = Vec::with_capacity(ips.len());
  for (idx, ip) in ips.into_iter().enumerate() {
    let for_ip = parse_forwarded_ip_token(ip)?;
    chain.push(ForwardedEntry {
      for_node: ForwardedNode {
        ip: Some(for_ip),
        port: None,
        raw: ForwardedNodeRaw::Ip,
      },
      proto: if idx == last_idx { xf_proto.clone() } else { None },
      host: if idx == last_idx { authoritative_host.clone() } else { None },
      by: None,
    });
  }
  Ok(chain)
}

/// Parse Forwarded header according to RFC 7239.
/// This is more complex than X-Forwarded-For due to its richer syntax and potential for multiple field-lines.
fn parse_forwarded_header(headers: &HeaderMap) -> Result<Vec<ForwardedEntry>> {
  let forwarded = join_header_values(headers, header::FORWARDED)?.ok_or_else(|| anyhow!("forwarded header missing"))?;
  let mut chain = Vec::new();
  for entry in split_respecting_quotes(&forwarded, b',')
    .into_iter()
    .filter(|entry| !entry.is_empty())
  {
    let forwarded_entry = parse_forwarded_header_entry(entry)?;
    chain.push(forwarded_entry);
  }
  Ok(chain)
}

/// Parse a single entry in Forwarded header, which may contain multiple parameters separated by ';'.
fn parse_forwarded_header_entry(entry: &str) -> Result<ForwardedEntry> {
  let mut for_node = None;
  let mut proto = None;
  let mut host = None;
  let mut by = None;
  for param in split_respecting_quotes(entry, b';')
    .into_iter()
    .filter(|param| !param.is_empty())
  {
    let Some((key, value)) = param.split_once('=') else {
      continue;
    };
    let key = key.trim().to_ascii_lowercase();
    let value = value.trim();
    match key.as_str() {
      "for" => {
        if for_node.is_some() {
          return Err(anyhow!("forwarded header entry contains duplicate for= parameter"));
        }
        for_node = Some(parse_forwarded_node(value)?);
      }
      "proto" => {
        if proto.is_some() {
          return Err(anyhow!("forwarded header entry contains duplicate proto= parameter"));
        }
        proto = Some(unquote_http_value(value)?);
      }
      "host" => {
        if host.is_some() {
          return Err(anyhow!("forwarded header entry contains duplicate host= parameter"));
        }
        host = Some(unquote_http_value(value)?);
      }
      "by" => {
        if by.is_some() {
          return Err(anyhow!("forwarded header entry contains duplicate by= parameter"));
        }
        by = Some(unquote_http_value(value)?);
      }
      _ => continue, // Ignore unrecognized parameters
    }
  }
  let Some(for_node) = for_node else {
    return Err(anyhow!("forwarded header entry missing for= parameter"));
  };
  Ok(ForwardedEntry {
    for_node,
    proto,
    host,
    by,
  })
}

/// Check consistency between Forwarded and X-Forwarded-* headers. This is a sanity check to prevent trusting a forged Forwarded header when X-Forwarded-For is also present and inconsistent.
fn forwarded_is_consistent(forwarded: &[ForwardedEntry], xff_chain: &[ForwardedEntry]) -> bool {
  // Length check
  if forwarded.len() != xff_chain.len() {
    return false;
  }
  // IP chain check
  if !forwarded
    .iter()
    .map(|entry| entry.for_node.ip_addr())
    .eq(xff_chain.iter().map(|entry| entry.for_node.ip_addr()))
  {
    return false;
  }

  // Optional proto check for the last entry, if proto is present in both headers. This is a sanity check to prevent trusting a forged Forwarded header when X-Forwarded-Proto is also present and inconsistent.
  let proto = xff_chain.last().and_then(|entry| entry.proto.as_deref());
  let forwarded_proto = forwarded.last().and_then(|entry| entry.proto.as_deref());
  if let Some(fp) = forwarded_proto && let Some(p) = proto && !fp.eq_ignore_ascii_case(p.trim()) {
    return false;
  }

  true
}

/* --------------------------------------------------------------------------------------------------------- */
/* Generic parsing helpers                                                                                 */
/* --------------------------------------------------------------------------------------------------------- */

/// Get the first header value as string if exist
fn first_header_value(headers: &HeaderMap, key: impl AsHeaderName) -> Result<Option<String>> {
  let Some(first) = headers.get(key) else {
    return Ok(None);
  };
  first
    .to_str()
    .map(|value| Some(value.to_string()))
    .map_err(|e| anyhow!("invalid header value: {e}"))
}

/// Join multiple header values into a single comma-separated string, if exist
fn join_header_values(headers: &HeaderMap, key: impl AsHeaderName) -> Result<Option<String>> {
  let values = headers
    .get_all(key)
    .iter()
    .map(|value| value.to_str().map(|s| s.to_string()))
    .collect::<std::result::Result<Vec<_>, _>>()
    .map_err(|e| anyhow!("invalid header value: {e}"))?;
  if values.is_empty() {
    Ok(None)
  } else {
    Ok(Some(values.join(", ")))
  }
}

/// Split a header value by a delimiter while respecting quoted substrings.
fn split_respecting_quotes(input: &str, delimiter: u8) -> Vec<&str> {
  let mut segments = Vec::new();
  let mut start = 0usize;
  let mut in_quotes = false;
  let mut escaped = false;
  for (idx, byte) in input.as_bytes().iter().copied().enumerate() {
    if escaped {
      escaped = false;
      continue;
    }
    match byte {
      b'\\' if in_quotes => escaped = true,
      b'"' => in_quotes = !in_quotes,
      b if b == delimiter && !in_quotes => {
        segments.push(input[start..idx].trim());
        start = idx + 1;
      }
      _ => {}
    }
  }
  segments.push(input[start..].trim());
  segments
}

/// Unquote a quoted-string value and unescape quoted-pair according to RFC 7230.
fn unquote_http_value(value: &str) -> Result<String> {
  let trimmed = value.trim();
  if !trimmed.starts_with('"') {
    return Ok(trimmed.to_string());
  }
  let Some(inner) = trimmed.strip_prefix('"').and_then(|s| s.strip_suffix('"')) else {
    return Err(anyhow!("unterminated quoted-string `{trimmed}`"));
  };
  let mut result = String::with_capacity(inner.len());
  let mut escaped = false;
  for ch in inner.chars() {
    if escaped {
      result.push(ch);
      escaped = false;
      continue;
    }
    if ch == '\\' {
      escaped = true;
      continue;
    }
    result.push(ch);
  }
  if escaped {
    return Err(anyhow!("unterminated escape sequence in quoted-string `{trimmed}`"));
  }
  Ok(result)
}

/// Parse a token in Forwarded header that is supposed to represent a client IP, which can be an IP address, "unknown", or obfuscated identifier.
fn parse_forwarded_ip_token(token: &str) -> Result<IpAddr> {
  match parse_forwarded_node(token)? {
    ForwardedNode { ip: Some(ip), .. } => Ok(ip),
    ForwardedNode { ip: None, .. } => Err(anyhow!("forwarded node `{token}` is not an IP address")),
  }
}

/// Parse the value of `for=` parameter in Forwarded header, which can be an IP address (with optional port), "unknown", or obfuscated identifier, according to RFC 7239.
fn parse_forwarded_node(token: &str) -> Result<ForwardedNode> {
  let trimmed = unquote_http_value(token)?;
  if trimmed.eq_ignore_ascii_case("unknown") {
    return Ok(ForwardedNode {
      ip: None,
      port: None,
      raw: ForwardedNodeRaw::Unknown,
    });
  }
  // RFC 7239 requires IPv6 literals with a port to be bracketed (e.g. `[2001:db8::1]:443`).
  // Applying rsplit_once(':') unconditionally would mis-parse an unbracketed IPv6 such as
  // `2001:db8::4711` as `ip=2001:db8::` + `port=4711`. So only split on ':' when the token
  // is bracketed, or when it contains exactly one ':' (IPv4 / unknown / obfuscated).
  if trimmed.starts_with('[') {
    if let Some((node, port)) = trimmed.rsplit_once(':') {
      if let Some(inner) = node.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
        let ip = canonicalize_ip(IpAddr::from_str(inner).map_err(|e| anyhow!("invalid forwarded address `{token}`: {e}"))?);
        return Ok(ForwardedNode {
          ip: Some(ip),
          port: Some(parse_forwarded_port(port, token)?.to_string()),
          raw: ForwardedNodeRaw::Ip,
        });
      }
    }
  } else if trimmed.matches(':').count() == 1 {
    if let Some((node, port)) = trimmed.rsplit_once(':') {
      if node.eq_ignore_ascii_case("unknown") {
        return Ok(ForwardedNode {
          ip: None,
          port: Some(port.to_string()),
          raw: ForwardedNodeRaw::Unknown,
        });
      }
      if node.starts_with('_') {
        return Ok(ForwardedNode {
          ip: None,
          port: Some(port.to_string()),
          raw: ForwardedNodeRaw::Obfuscated(node.to_string()),
        });
      }
      if let Ok(ip) = IpAddr::from_str(node) {
        return Ok(ForwardedNode {
          ip: Some(canonicalize_ip(ip)),
          port: Some(parse_forwarded_port(port, token)?.to_string()),
          raw: ForwardedNodeRaw::Ip,
        });
      }
    }
  }

  if let Some(inner) = trimmed.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
    let ip = IpAddr::from_str(inner).map_err(|e| anyhow!("invalid forwarded address `{token}`: {e}"))?;
    Ok(ForwardedNode {
      ip: Some(canonicalize_ip(ip)),
      port: None,
      raw: ForwardedNodeRaw::Ip,
    })
  } else if trimmed.starts_with('_') {
    Ok(ForwardedNode {
      ip: None,
      port: None,
      raw: ForwardedNodeRaw::Obfuscated(trimmed),
    })
  } else {
    let ip = IpAddr::from_str(&trimmed).map_err(|e| anyhow!("invalid forwarded address `{token}`: {e}"))?;
    Ok(ForwardedNode {
      ip: Some(canonicalize_ip(ip)),
      port: None,
      raw: ForwardedNodeRaw::Ip,
    })
  }
}

/// Parse the port part of `for=` parameter in Forwarded header, ensuring it is a valid u16.
fn parse_forwarded_port(port: &str, token: &str) -> Result<u16> {
  port
    .parse::<u16>()
    .map_err(|e| anyhow!("invalid forwarded port in `{token}`: {e}"))
}

/* --------------------------------------------------------------------------------------------------------- */
/* Chain helpers and output generation                                                                     */
/* --------------------------------------------------------------------------------------------------------- */

/// Canonicalize IP address to ensure consistent matching against trusted proxy list.
fn canonicalize_ip(ip: IpAddr) -> IpAddr {
  SocketAddr::new(ip, 0).to_canonical().ip()
}

/// Build a ForwardedEntry for the immediate peer, which represents this proxy's authoritative view of the client connection. This is used as the basis for forwarding chain normalization and generation.
fn build_peer_forwarded_entry(headers: &HeaderMap, peer_ip: IpAddr, tls: bool, original_uri: &Uri) -> ForwardedEntry {
  ForwardedEntry {
    for_node: ForwardedNode {
      ip: Some(peer_ip),
      port: None,
      raw: ForwardedNodeRaw::Ip,
    },
    proto: if tls { Some("https".into()) } else { Some("http".into()) },
    host: host_from_uri_or_host_header(original_uri, headers.get(header::HOST)).ok(),
    by: None,
  }
}

/// Check if the given IP is in the list of trusted proxies.
fn is_trusted_proxy(ip: &IpAddr, trusted_forwarded_proxies: &[IpNet]) -> bool {
  let canonical = canonicalize_ip(*ip);
  trusted_forwarded_proxies.iter().any(|net| net.contains(&canonical))
}

/// Check if the given forwarding entry represents a trusted proxy hop that can be skipped in the forwarding chain. This is true if the `for` parameter is an IP address that is in the trusted proxies list.
fn entry_is_trusted_proxy(entry: &ForwardedEntry, trusted_forwarded_proxies: &[IpNet]) -> bool {
  entry
    .for_node
    .ip_addr()
    .map(|ip| is_trusted_proxy(&ip, trusted_forwarded_proxies))
    .unwrap_or(false)
}

/// Convert a forwarding chain of ForwardedEntry into a list of IP strings for X-Forwarded-For header. This returns None if any entry in the chain is not an IP address, which indicates that we cannot represent this chain in X-Forwarded-For and should fall back to a peer-only view.
fn forwarded_chain_to_xff(chain: &[ForwardedEntry]) -> Option<Vec<String>> {
  chain
    .iter()
    .map(|entry| entry.for_node.ip_addr().map(|ip| ip.to_string()))
    .collect::<Option<Vec<_>>>()
}

/// Overwrite a header with a single value that is a comma-separated concatenation of the given values. This is used to update X-Forwarded-For with the normalized chain.
fn overwrite_header_with_csv(headers: &mut HeaderMap, key: HeaderName, values: &[String]) -> Result<()> {
  headers.remove(&key);
  headers.insert(key, HeaderValue::from_str(&values.join(", "))?);
  Ok(())
}

/// Generate an RFC 7239 `Forwarded` header from the normalized forwarding chain.
/// This function assumes that the forwarding chain is present and well-formed.
/// Each hop is emitted with a `for=` parameter, and may additionally include
/// `proto=`, `host=`, and `by=` parameters when those fields are present.
pub(super) fn generate_forwarded_header(normalized_forwarding_chain: &[ForwardedEntry]) -> Result<String> {
  if normalized_forwarding_chain.is_empty() {
    return Err(anyhow!("No forwarding chain found for Forwarded generation"));
  }

  // for= is always present. proto=, host=, and by= might not be present.
  let elements = normalized_forwarding_chain
    .iter()
    .map(|entry| {
      let mut parts = vec![format!("for={}", format_forwarded_node(&entry.for_node)?)];
      if let Some(proto) = &entry.proto {
        parts.push(format!("proto={}", format_forwarded_param_value(proto)));
      }
      if let Some(host) = &entry.host {
        parts.push(format!("host={}", format_forwarded_param_value(host)));
      }
      if let Some(by) = &entry.by {
        parts.push(format!("by={}", format_forwarded_param_value(by)));
      }
      Ok(parts.join(";"))
    })
    .collect::<Result<Vec<_>>>()?;

  Ok(elements.join(", "))
}

/// Return true if `c` is an RFC 7230 tchar, i.e. may appear unquoted in a token.
fn is_tchar(c: char) -> bool {
  matches!(
    c,
    '!' | '#' | '$' | '%' | '&' | '\'' | '*' | '+' | '-' | '.' | '^' | '_' | '`' | '|' | '~'
  ) || c.is_ascii_alphanumeric()
}

/// Format a Forwarded parameter value (proto/host/by). If the value contains any
/// non-tchar byte (e.g. `:` for ports, `[`/`]` for IPv6 literals), wrap it in a
/// quoted-string and escape `\` and `"` as RFC 7230 quoted-pair. Otherwise emit as-is.
fn format_forwarded_param_value(value: &str) -> String {
  if !value.is_empty() && value.chars().all(is_tchar) {
    return value.to_string();
  }
  let mut out = String::with_capacity(value.len() + 2);
  out.push('"');
  for ch in value.chars() {
    if ch == '\\' || ch == '"' {
      out.push('\\');
    }
    out.push(ch);
  }
  out.push('"');
  out
}

/// Format the for= value in Forwarded header according to RFC 7239, which may require quoting and bracketing for IPv6 addresses.
fn format_forwarded_node(node: &ForwardedNode) -> Result<String> {
  match (&node.raw, node.ip, node.port.as_deref()) {
    (ForwardedNodeRaw::Ip, Some(IpAddr::V4(v4)), None) => Ok(v4.to_string()),
    (ForwardedNodeRaw::Ip, Some(IpAddr::V4(v4)), Some(port)) => Ok(format!("\"{}:{}\"", v4, port)),
    (ForwardedNodeRaw::Ip, Some(IpAddr::V6(v6)), None) => Ok(format!("\"[{}]\"", v6)),
    (ForwardedNodeRaw::Ip, Some(IpAddr::V6(v6)), Some(port)) => Ok(format!("\"[{}]:{}\"", v6, port)),
    (ForwardedNodeRaw::Unknown, None, None) => Ok("unknown".to_string()),
    (ForwardedNodeRaw::Unknown, None, Some(port)) => Ok(format!("\"unknown:{}\"", port)),
    (ForwardedNodeRaw::Obfuscated(node), None, None) => Ok(node.clone()),
    (ForwardedNodeRaw::Obfuscated(node), None, Some(port)) => Ok(format!("\"{}:{}\"", node, port)),
    _ => Err(anyhow!("invalid forwarded node state")),
  }
}

#[cfg(test)]
mod tests {
  use super::*;

  fn trusted(cidrs: &[&str]) -> Vec<IpNet> {
    cidrs.iter().map(|c| c.parse::<IpNet>().unwrap()).collect()
  }

  #[test]
  fn untrusted_peer_ignores_incoming_forwarding_headers() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));
    headers.insert(X_FORWARDED_FOR, HeaderValue::from_static("1.2.3.4"));
    headers.insert(X_FORWARDED_PROTO, HeaderValue::from_static("https"));
    headers.insert(X_FORWARDED_PORT, HeaderValue::from_static("443"));
    headers.insert(X_FORWARDED_HOST, HeaderValue::from_static("spoofed.example"));
    headers.insert(
      header::FORWARDED,
      HeaderValue::from_static("for=1.2.3.4;proto=https;host=app.example"),
    );

    add_forwarding_header(
      &mut headers,
      &"203.0.113.10:4321".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/demo?q=1"),
      &[],
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "203.0.113.10");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "203.0.113.10");
    assert_eq!(headers.get(X_FORWARDED_PROTO).unwrap(), "http");
    assert_eq!(headers.get(X_FORWARDED_PORT).unwrap(), "8080");
    assert_eq!(headers.get(X_FORWARDED_HOST).unwrap(), "app.example");
    assert_eq!(
      headers.get(header::FORWARDED).unwrap(),
      "for=203.0.113.10;proto=http;host=app.example"
    );
  }

  #[test]
  fn trusted_proxy_keeps_verified_trusted_suffix() {
    let mut headers = HeaderMap::new();
    headers.insert(X_FORWARDED_FOR, HeaderValue::from_static("198.51.100.10, 10.9.0.4"));

    add_forwarding_header(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8443".parse().unwrap(),
      true,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "198.51.100.10, 10.9.0.4, 10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "198.51.100.10");
    assert_eq!(headers.get(X_FORWARDED_PROTO).unwrap(), "https");
  }

  #[test]
  fn trusted_proxy_stops_at_last_non_trusted_hop() {
    let mut headers = HeaderMap::new();
    headers.insert(X_FORWARDED_FOR, HeaderValue::from_static("198.51.100.10, 203.0.113.20"));

    add_forwarding_header(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "203.0.113.20, 10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "203.0.113.20");
  }

  #[test]
  fn trusted_proxy_uses_forwarded_when_xff_missing() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));
    headers.insert(header::FORWARDED, HeaderValue::from_static("for=198.51.100.10, for=10.9.0.4"));

    add_forwarding_header(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "198.51.100.10, 10.9.0.4, 10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "198.51.100.10");
    assert_eq!(
      headers.get(header::FORWARDED).unwrap(),
      "for=198.51.100.10, for=10.9.0.4, for=10.1.2.3;proto=http;host=app.example"
    );
  }

  #[test]
  fn trusted_proxy_falls_back_to_xff_when_forwarded_chain_is_inconsistent() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));
    headers.insert(X_FORWARDED_FOR, HeaderValue::from_static("198.51.100.10"));
    headers.insert(
      header::FORWARDED,
      HeaderValue::from_static("for=203.0.113.20;proto=https;host=app.example"),
    );

    add_forwarding_header(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "198.51.100.10, 10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "198.51.100.10");
    assert_eq!(
      headers.get(header::FORWARDED).unwrap(),
      "for=198.51.100.10, for=10.1.2.3;proto=http;host=app.example"
    );
  }

  #[test]
  fn trusted_proxy_accepts_multiple_xff_field_lines() {
    let mut headers = HeaderMap::new();
    headers.append(X_FORWARDED_FOR, HeaderValue::from_static("198.51.100.10"));
    headers.append(X_FORWARDED_FOR, HeaderValue::from_static("10.9.0.4"));

    add_forwarding_header(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "198.51.100.10, 10.9.0.4, 10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "198.51.100.10");
  }

  #[test]
  fn trusted_proxy_accepts_multiple_forwarded_field_lines() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));
    headers.append(header::FORWARDED, HeaderValue::from_static("for=198.51.100.10"));
    headers.append(header::FORWARDED, HeaderValue::from_static("for=10.9.0.4"));

    add_forwarding_header(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "198.51.100.10, 10.9.0.4, 10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "198.51.100.10");
    assert_eq!(
      headers.get(header::FORWARDED).unwrap(),
      "for=198.51.100.10, for=10.9.0.4, for=10.1.2.3;proto=http;host=app.example"
    );
  }

  #[test]
  fn ipv6_peer_produces_correctly_formatted_headers() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));

    add_forwarding_header(
      &mut headers,
      &"[2001:db8::1]:4321".parse().unwrap(),
      &"[::1]:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &[],
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "2001:db8::1");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "2001:db8::1");
    assert_eq!(headers.get(X_FORWARDED_HOST).unwrap(), "app.example");
    assert!(!headers.contains_key(header::FORWARDED));
  }

  #[test]
  fn x_forwarded_host_uses_uri_authority_for_absolute_form() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("host-header.example"));
    headers.insert(X_FORWARDED_HOST, HeaderValue::from_static("spoofed.example"));

    add_forwarding_header(
      &mut headers,
      &"203.0.113.10:4321".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &"http://uri-authority.example:8080/demo?q=1".parse::<Uri>().unwrap(),
      &[],
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_HOST).unwrap(), "uri-authority.example:8080");
  }

  #[test]
  fn x_forwarded_host_is_cleared_when_original_host_is_unavailable() {
    let mut headers = HeaderMap::new();
    headers.insert(X_FORWARDED_HOST, HeaderValue::from_static("spoofed.example"));

    add_forwarding_header(
      &mut headers,
      &"203.0.113.10:4321".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/demo?q=1"),
      &[],
    )
    .unwrap();

    assert!(headers.get(X_FORWARDED_HOST).is_none());
  }

  #[test]
  fn generate_forwarded_header_quotes_bracketed_ipv6_for_node() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));

    add_forwarding_header(
      &mut headers,
      &"[2001:db8::1]:4321".parse().unwrap(),
      &"[::1]:8080".parse().unwrap(),
      true,
      &Uri::from_static("/"),
      &[],
    )
    .unwrap();

    let normalized_chain = vec![ForwardedEntry {
      for_node: ForwardedNode {
        ip: Some("2001:db8::1".parse().unwrap()),
        port: None,
        raw: ForwardedNodeRaw::Ip,
      },
      proto: Some("https".into()),
      host: Some("app.example".into()),
      by: None,
    }];
    let forwarded = generate_forwarded_header(&normalized_chain).unwrap();
    assert_eq!(forwarded, "for=\"[2001:db8::1]\";proto=https;host=app.example");
  }

  #[test]
  fn ipv4_mapped_ipv6_peer_is_canonicalized() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));

    // ::ffff:10.1.2.3 should be canonicalized to 10.1.2.3
    add_forwarding_header(
      &mut headers,
      &"[::ffff:10.1.2.3]:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &[],
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "10.1.2.3");
  }

  #[test]
  fn ipv4_mapped_ipv6_matches_trusted_v4_cidr() {
    let mut headers = HeaderMap::new();
    headers.insert(X_FORWARDED_FOR, HeaderValue::from_static("198.51.100.10"));

    // Peer is ::ffff:10.1.2.3, trusted CIDR is 10.0.0.0/8 (IPv4)
    add_forwarding_header(
      &mut headers,
      &"[::ffff:10.1.2.3]:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "198.51.100.10, 10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "198.51.100.10");
  }

  #[test]
  fn trusted_proxy_parses_forwarded_with_ipv6() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));
    headers.insert(
      header::FORWARDED,
      HeaderValue::from_static("for=\"[2001:db8::1]\";proto=https;host=app.example"),
    );

    add_forwarding_header(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "2001:db8::1, 10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "2001:db8::1");
  }

  #[test]
  fn xff_with_empty_segments_assigns_proto_to_last_valid_entry() {
    let mut headers = HeaderMap::new();
    headers.insert(X_FORWARDED_FOR, HeaderValue::from_static("198.51.100.10, , 203.0.113.20"));
    headers.insert(X_FORWARDED_PROTO, HeaderValue::from_static("https"));

    add_forwarding_header(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    // proto should be assigned to 203.0.113.20 (the last valid entry), not lost
    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "203.0.113.20, 10.1.2.3");
  }

  #[test]
  fn trusted_proxy_accepts_forwarded_with_port() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));
    headers.insert(
      header::FORWARDED,
      HeaderValue::from_static("for=\"192.0.2.43:4711\", for=10.9.0.4"),
    );

    add_forwarding_header(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "192.0.2.43, 10.9.0.4, 10.1.2.3");
    assert_eq!(
      headers.get(header::FORWARDED).unwrap(),
      "for=\"192.0.2.43:4711\", for=10.9.0.4, for=10.1.2.3;proto=http;host=app.example"
    );
  }

  #[test]
  fn trusted_proxy_with_forwarded_unknown_falls_back_to_peer_only() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));
    headers.insert(header::FORWARDED, HeaderValue::from_static("for=unknown, for=10.9.0.4"));

    add_forwarding_header(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "10.1.2.3");
    assert_eq!(
      headers.get(header::FORWARDED).unwrap(),
      "for=10.1.2.3;proto=http;host=app.example"
    );
  }

  #[test]
  fn parse_forwarded_node_accepts_unbracketed_ipv6_without_port() {
    // An unbracketed IPv6 literal must not be mis-parsed as `ip + :port`:
    // the trailing `::4711` is a valid hextet, not a port.
    let node = parse_forwarded_node("2001:db8::4711").unwrap();
    assert_eq!(node.ip, Some("2001:db8::4711".parse::<IpAddr>().unwrap()));
    assert_eq!(node.port, None);
    assert_eq!(node.raw, ForwardedNodeRaw::Ip);
  }

  #[test]
  fn parse_forwarded_node_accepts_bracketed_ipv6_with_port() {
    // RFC 7239 requires IPv6 addresses with a port to be bracketed.
    let node = parse_forwarded_node("\"[2001:db8::1]:443\"").unwrap();
    assert_eq!(node.ip, Some("2001:db8::1".parse::<IpAddr>().unwrap()));
    assert_eq!(node.port.as_deref(), Some("443"));
    assert_eq!(node.raw, ForwardedNodeRaw::Ip);
  }

  #[test]
  fn parse_forwarded_node_rejects_unbracketed_ipv6_with_port() {
    // Without brackets, the trailing colon-number must not be treated as a port.
    // `2001:db8::1:443` is itself a valid IPv6 literal and should parse as such.
    let node = parse_forwarded_node("2001:db8::1:443").unwrap();
    assert_eq!(node.ip, Some("2001:db8::1:443".parse::<IpAddr>().unwrap()));
    assert_eq!(node.port, None);
  }

  #[test]
  fn parse_forwarded_node_still_parses_ipv4_with_port() {
    let node = parse_forwarded_node("192.0.2.1:443").unwrap();
    assert_eq!(node.ip, Some("192.0.2.1".parse::<IpAddr>().unwrap()));
    assert_eq!(node.port.as_deref(), Some("443"));
  }

  #[test]
  fn format_forwarded_param_value_leaves_token_unquoted() {
    assert_eq!(format_forwarded_param_value("https"), "https");
    assert_eq!(format_forwarded_param_value("example.com"), "example.com");
  }

  #[test]
  fn format_forwarded_param_value_quotes_host_with_port() {
    // `:` is not a tchar, so `host=example.com:8443` must be emitted as quoted-string.
    assert_eq!(format_forwarded_param_value("example.com:8443"), "\"example.com:8443\"");
  }

  #[test]
  fn format_forwarded_param_value_quotes_ipv6_literal() {
    assert_eq!(format_forwarded_param_value("[2001:db8::1]"), "\"[2001:db8::1]\"");
  }

  #[test]
  fn format_forwarded_param_value_escapes_quote_and_backslash() {
    assert_eq!(format_forwarded_param_value("a\"b\\c"), "\"a\\\"b\\\\c\"");
  }

  #[test]
  fn generate_forwarded_header_quotes_host_with_port() {
    let chain = vec![ForwardedEntry {
      for_node: ForwardedNode {
        ip: Some("192.0.2.1".parse().unwrap()),
        port: None,
        raw: ForwardedNodeRaw::Ip,
      },
      proto: Some("https".into()),
      host: Some("example.com:8443".into()),
      by: None,
    }];
    assert_eq!(
      generate_forwarded_header(&chain).unwrap(),
      "for=192.0.2.1;proto=https;host=\"example.com:8443\""
    );
  }
}
