use anyhow::{Result, anyhow};
use http::{HeaderMap, HeaderValue, Uri, header, header::AsHeaderName};
use ipnet::IpNet;
use std::{
  borrow::Cow,
  fmt::Write as _,
  net::{IpAddr, Ipv4Addr, SocketAddr},
  str::FromStr,
};

use crate::log::*;

use super::{
  super::canonical_address::ToCanonical,
  common::{add_header_entry_overwrite_if_exist, make_cookie_single_line},
  header_defs::*,
};

fn overwrite_x_forwarded_host_from_original(headers: &mut HeaderMap, authoritative_host: Option<&str>) -> Result<()> {
  match authoritative_host {
    // insert() replaces all existing values, identical to add_header_entry_overwrite_if_exist,
    // and builds the HeaderValue straight from the borrowed str (no intermediate String).
    Some(host) => {
      headers.insert(X_FORWARDED_HOST, HeaderValue::from_str(host)?);
    }
    None => {
      headers.remove(X_FORWARDED_HOST);
    }
  }
  Ok(())
}

/* --------------------------------------------------------------------------------------------------------- */
/* Forwarding header normalization model                                                                   */
/* --------------------------------------------------------------------------------------------------------- */

/// Internal representation of the forwarding chain used by rpxy.
///
/// The flow is:
/// 1. Parse `Forwarded` and/or `X-Forwarded-*` into `ForwardedEntry`
/// 2. Append the immediate peer as rpxy's authoritative latest hop
/// 3. Trim trusted proxy hops from the right-hand side
/// 4. Regenerate outgoing `X-Forwarded-*` / `Forwarded` from the normalized chain
///
/// Keeping this representation in one place makes the trust-boundary logic
/// easier to audit than passing partially parsed headers across multiple helpers.

/// An entry in Forwarded header with only the parameters relevant for forwarding chain normalization and consistency check.
#[derive(Clone, Debug, PartialEq, Eq)]
struct ForwardedNode {
  ip: Option<IpAddr>,
  port: Option<String>,
  raw: ForwardedNodeRaw,
}

#[derive(Clone, Debug, PartialEq, Eq)]
enum ForwardedNodeRaw {
  Ip,
  Unknown,
  Obfuscated(String),
}

impl ForwardedNode {
  fn ip_addr(&self) -> Option<IpAddr> {
    self.ip
  }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(super) struct ForwardedEntry {
  /// for=:
  /// For Forwarded Header: this is optional in the RFC, but we require it for each entry to be able to build the forwarding chain. If missing, the entry is considered invalid.
  for_node: ForwardedNode,
  /// proto=, When generated from incoming X-Forwarded-For, this is always None except for the last entry which was generated by the previous hop proxy. This is used for consistency check against X-Forwarded-Proto.
  proto: Option<String>,
  /// host=, When generated from incoming X-Forwarded-For, this is always None
  host: Option<String>,
  /// by=, When generated from incoming X-Forwarded-For, this is always None.
  by: Option<String>,
}

/// Add or update forwarding headers like `x-forwarded-for`.
/// If only `forwarded` header exists, it will update `x-forwarded-for` with the proxy chain.
/// If both `x-forwarded-for` and `forwarded` headers exist, it will update `x-forwarded-for` first and then add `forwarded` header.
/// If the immediate peer is in trusted_forwarded_proxies,
/// it will recursively trust the incoming forwarding headers and append the immediate peer IP to the end of the chain.
/// Otherwise, it will ignore incoming forwarding headers and start a new chain with the immediate peer IP.
pub(in crate::message_handler) fn add_forwarding_header(
  headers: &mut HeaderMap,
  client_addr: &SocketAddr,
  listen_addr: &SocketAddr,
  tls: bool,
  original_uri: &Uri,
  authoritative_host: Option<&str>,
  trusted_forwarded_proxies: &[IpNet],
) -> Result<()> {
  let peer_ip = canonicalize_ip(client_addr.to_canonical().ip());
  let has_forwarded = headers.contains_key(header::FORWARDED);
  let normalized_chain = normalize_forwarding_chain(headers, &peer_ip, tls, authoritative_host, trusted_forwarded_proxies);

  let (normalized_chain, xff_csv, xff_first_len) = match xff_csv_from_chain(&normalized_chain) {
    Some((csv, first_len)) => (normalized_chain, csv, first_len),
    None => {
      warn!("Normalized forwarding chain contains non-IP hops; falling back to peer-only forwarding view");
      // Only this rare fallback needs a freshly built peer entry, so build it here instead
      // of eagerly on every request.
      let peer_entry = build_peer_forwarded_entry(peer_ip, tls, authoritative_host);
      let mut csv = String::new();
      push_ip_addr(&mut csv, &peer_ip);
      let first_len = csv.len();
      (vec![peer_entry], csv, first_len)
    }
  };

  // For X-Real-IP: slice the first element out of the already-rendered CSV (one copy),
  // before X-Forwarded-For takes ownership of the whole buffer without copying. The value
  // equals formatting normalized_chain.first()'s IP directly, as before. Inserted further
  // below to keep the header insertion order unchanged.
  let x_real_ip_value = HeaderValue::from_str(&xff_csv[..xff_first_len])?;

  // Update X-Forwarded-For with normalized chain. insert() replaces all previous values,
  // identical to the remove+insert it replaces; try_from(String) takes ownership of the
  // CSV buffer without re-copying its bytes.
  headers.insert(X_FORWARDED_FOR, HeaderValue::try_from(xff_csv)?);

  // Preserve/update Forwarded only if it was present on input. If callers want to force
  // Forwarded generation, apply_upstream_options_to_header() will regenerate it later.
  if has_forwarded {
    match generate_forwarded_header(&normalized_chain) {
      Ok(forwarded_value) => add_header_entry_overwrite_if_exist(headers, header::FORWARDED, forwarded_value)?,
      Err(e) => warn!("Failed to update existing Forwarded header for consistency: {}", e),
    }
  } else {
    headers.remove(header::FORWARDED);
  }

  // Single line cookie header
  // TODO: This should be only for HTTP/1.1. For 2+, this can be multi-lined.
  make_cookie_single_line(headers)?;

  // Always overwrite these headers with rpxy's authoritative downstream view.
  // Constant values use HeaderValue::from_static (no runtime byte validation or allocation);
  // the port uses HeaderValue::from(u16) (lighter than to_string() + parse). insert() replaces
  // any existing values with a single value, matching add_header_entry_overwrite_if_exist.
  headers.insert(
    X_FORWARDED_PROTO,
    HeaderValue::from_static(if tls { "https" } else { "http" }),
  );
  headers.insert(X_FORWARDED_PORT, HeaderValue::from(listen_addr.port()));

  /////////// As Nginx-Proxy
  // x-real-ip: pre-built above from the first element of the XFF CSV.
  headers.insert(X_REAL_IP, x_real_ip_value);
  // x-forwarded-ssl
  headers.insert(X_FORWARDED_SSL, HeaderValue::from_static(if tls { "on" } else { "off" }));
  // x-original-uri
  add_header_entry_overwrite_if_exist(headers, X_ORIGINAL_URI, original_uri.to_string())?;
  // x-forwarded-host
  overwrite_x_forwarded_host_from_original(headers, authoritative_host)?;
  // proxy
  headers.insert(PROXY, HeaderValue::from_static(""));

  Ok(())
}

/* --------------------------------------------------------------------------------------------------------- */
/* High-level forwarding flow                                                                              */
/* --------------------------------------------------------------------------------------------------------- */

/// Normalize forwarding chain based on trusted proxies configuration.
fn normalize_forwarding_chain(
  headers: &HeaderMap,
  peer_ip: &IpAddr,
  tls: bool,
  authoritative_host: Option<&str>,
  trusted_forwarded_proxies: &[IpNet],
) -> Vec<ForwardedEntry> {
  let peer_entry = build_peer_forwarded_entry(*peer_ip, tls, authoritative_host);
  if !is_trusted_proxy(peer_ip, trusted_forwarded_proxies) {
    return vec![peer_entry];
  }

  let mut forwarding_chain = match extract_forwarding_chain_from_headers(headers, None) {
    Ok(Some(chain)) if !chain.is_empty() => chain,
    Ok(_) => {
      return vec![peer_entry];
    }
    Err(e) => {
      warn!("Ignoring incoming forwarding headers from trusted proxy due to parse failure: {e}");
      return vec![peer_entry];
    }
  };

  // Append the immediate peer as the last hop in the chain, which is the authoritative view of this proxy.
  forwarding_chain.push(peer_entry);
  let normalized_chain = reduce_trusted_proxy_chain(forwarding_chain, trusted_forwarded_proxies);
  if normalized_chain.is_empty() {
    // Defensive only: reduce_trusted_proxy_chain keeps at least the peer hop appended above.
    // Rebuilding here (instead of cloning the peer entry eagerly on every request) keeps
    // the guard at zero steady-state cost.
    return vec![build_peer_forwarded_entry(*peer_ip, tls, authoritative_host)];
  }
  normalized_chain
}

/// Extract forwarding information chain from Forwarded or X-Forwarded-For/Proto headers.
/// Returns None if neither header is present.
/// If both are present, prefer Forwarded only when it is consistent with the auxiliary X-Forwarded-* view.
pub(super) fn extract_forwarding_chain_from_headers(
  headers: &HeaderMap,
  authoritative_host: Option<&str>,
) -> Result<Option<Vec<ForwardedEntry>>> {
  let xff_chain = if headers.contains_key(X_FORWARDED_FOR) {
    Some(parse_x_forwarded_for_header(headers, authoritative_host)?)
  } else {
    None
  };
  let forwarded_chain = if headers.contains_key(header::FORWARDED) {
    match parse_forwarded_header(headers) {
      Ok(chain) => Some(chain),
      Err(e) if xff_chain.is_some() => {
        warn!("Ignoring invalid Forwarded header and falling back to X-Forwarded-For: {e}");
        None
      }
      Err(e) => return Err(e),
    }
  } else {
    None
  };

  match (forwarded_chain, xff_chain) {
    (Some(forwarded), Some(xff)) => {
      if forwarded_is_consistent(&forwarded, &xff) {
        Ok(Some(forwarded))
      } else {
        warn!("Incoming Forwarded header is inconsistent with X-Forwarded-* headers; falling back to X-Forwarded-For");
        Ok(Some(xff))
      }
    }
    (Some(forwarded), None) => Ok(Some(forwarded)),
    (None, Some(xff)) => Ok(Some(xff)),
    (None, None) => Ok(None),
  }
}

/// Use the trusted suffix at the end of the chain to locate the trust boundary.
/// This keeps the last non-trusted hop together with the trusted suffix after it,
/// and discards any earlier prefix to the left of that boundary.
/// We assume the immediate peer is always appended as the last hop.
pub(super) fn reduce_trusted_proxy_chain(
  mut chain: Vec<ForwardedEntry>,
  trusted_forwarded_proxies: &[IpNet],
) -> Vec<ForwardedEntry> {
  let mut idx = chain.len();
  while idx > 0 && entry_is_trusted_proxy(&chain[idx - 1], trusted_forwarded_proxies) {
    idx -= 1;
  }

  if idx == 0 {
    return chain;
  }
  let authoritative_idx = idx - 1;
  chain.drain(0..authoritative_idx);
  chain
}

/* --------------------------------------------------------------------------------------------------------- */
/* Incoming header parsing                                                                                 */
/* --------------------------------------------------------------------------------------------------------- */

/// Extract IP addresses from X-Forwarded-For header
fn parse_x_forwarded_for_header(headers: &HeaderMap, authoritative_host: Option<&str>) -> Result<Vec<ForwardedEntry>> {
  let xff = join_header_values(headers, X_FORWARDED_FOR)?.ok_or_else(|| anyhow!("x-forwarded-for header missing"))?;
  let xf_proto = first_header_value(headers, X_FORWARDED_PROTO)?.map(|s| s.trim().to_string());
  let ips: Vec<&str> = xff.split(',').map(str::trim).filter(|s| !s.is_empty()).collect();
  let last_idx = ips.len().saturating_sub(1);
  let mut chain = Vec::with_capacity(ips.len());
  for (idx, ip) in ips.into_iter().enumerate() {
    let for_ip = parse_forwarded_ip_token(ip)?;
    chain.push(ForwardedEntry {
      for_node: ForwardedNode {
        ip: Some(for_ip),
        port: None,
        raw: ForwardedNodeRaw::Ip,
      },
      proto: if idx == last_idx { xf_proto.clone() } else { None },
      host: if idx == last_idx { authoritative_host.map(str::to_owned) } else { None },
      by: None,
    });
  }
  Ok(chain)
}

/// Parse Forwarded header according to RFC 7239.
/// This is more complex than X-Forwarded-For due to its richer syntax and potential for multiple field-lines.
fn parse_forwarded_header(headers: &HeaderMap) -> Result<Vec<ForwardedEntry>> {
  let forwarded = join_header_values(headers, header::FORWARDED)?.ok_or_else(|| anyhow!("forwarded header missing"))?;
  let mut chain = Vec::new();
  for entry in split_respecting_quotes(&forwarded, b',')
    .into_iter()
    .filter(|entry| !entry.is_empty())
  {
    let forwarded_entry = parse_forwarded_header_entry(entry)?;
    chain.push(forwarded_entry);
  }
  Ok(chain)
}

/// Parse a single entry in Forwarded header, which may contain multiple parameters separated by ';'.
fn parse_forwarded_header_entry(entry: &str) -> Result<ForwardedEntry> {
  let mut for_node = None;
  let mut proto = None;
  let mut host = None;
  let mut by = None;
  for param in split_respecting_quotes(entry, b';')
    .into_iter()
    .filter(|param| !param.is_empty())
  {
    let Some((key, value)) = param.split_once('=') else {
      continue;
    };
    let key = key.trim().to_ascii_lowercase();
    let value = value.trim();
    match key.as_str() {
      "for" => {
        if for_node.is_some() {
          return Err(anyhow!("forwarded header entry contains duplicate for= parameter"));
        }
        for_node = Some(parse_forwarded_node(value)?);
      }
      "proto" => {
        if proto.is_some() {
          return Err(anyhow!("forwarded header entry contains duplicate proto= parameter"));
        }
        proto = Some(unquote_http_value(value)?);
      }
      "host" => {
        if host.is_some() {
          return Err(anyhow!("forwarded header entry contains duplicate host= parameter"));
        }
        host = Some(unquote_http_value(value)?);
      }
      "by" => {
        if by.is_some() {
          return Err(anyhow!("forwarded header entry contains duplicate by= parameter"));
        }
        by = Some(unquote_http_value(value)?);
      }
      _ => continue, // Ignore unrecognized parameters
    }
  }
  let Some(for_node) = for_node else {
    return Err(anyhow!("forwarded header entry missing for= parameter"));
  };
  Ok(ForwardedEntry {
    for_node,
    proto,
    host,
    by,
  })
}

/// Check consistency between Forwarded and X-Forwarded-* headers. This is a sanity check to prevent trusting a forged Forwarded header when X-Forwarded-For is also present and inconsistent.
fn forwarded_is_consistent(forwarded: &[ForwardedEntry], xff_chain: &[ForwardedEntry]) -> bool {
  // Length check
  if forwarded.len() != xff_chain.len() {
    return false;
  }
  // IP chain check
  if !forwarded
    .iter()
    .map(|entry| entry.for_node.ip_addr())
    .eq(xff_chain.iter().map(|entry| entry.for_node.ip_addr()))
  {
    return false;
  }

  // Optional proto check for the last entry, if proto is present in both headers. This is a sanity check to prevent trusting a forged Forwarded header when X-Forwarded-Proto is also present and inconsistent.
  let proto = xff_chain.last().and_then(|entry| entry.proto.as_deref());
  if let (Some(forwarded_proto), Some(proto)) = (forwarded.last().and_then(|entry| entry.proto.as_deref()), proto) {
    if !forwarded_proto.eq_ignore_ascii_case(proto.trim()) {
      return false;
    }
  }

  true
}

/* --------------------------------------------------------------------------------------------------------- */
/* Generic parsing helpers                                                                                 */
/* --------------------------------------------------------------------------------------------------------- */

/// Get the first header value as a borrowed `&str` if it exists.
fn first_header_value(headers: &HeaderMap, key: impl AsHeaderName) -> Result<Option<&str>> {
  let Some(first) = headers.get(key) else {
    return Ok(None);
  };
  first
    .to_str()
    .map(Some)
    .map_err(|e| anyhow!("invalid header value: {e}"))
}

/// Read the logical (comma-joined) value of a possibly multi-valued header.
///
/// The common single-field-line case borrows the header value (`Cow::Borrowed`, no allocation);
/// the rare multi-field-line case joins the lines with ", " exactly as before. Every value is
/// validated with `to_str`, so an unreadable line - including one after the first - still errors,
/// preserving the fail-closed behavior the proto readers rely on.
fn join_header_values<'a>(headers: &'a HeaderMap, key: impl AsHeaderName) -> Result<Option<Cow<'a, str>>> {
  let all = headers.get_all(key);
  let mut values = all.iter();
  let Some(first) = values.next() else {
    return Ok(None);
  };
  let first = first.to_str().map_err(|e| anyhow!("invalid header value: {e}"))?;
  let Some(second) = values.next() else {
    // Exactly one field-line: borrow it, no allocation.
    return Ok(Some(Cow::Borrowed(first)));
  };
  // Two or more field-lines: validate and join all of them (a later unreadable line still errors).
  let mut joined = String::from(first);
  for value in std::iter::once(second).chain(values) {
    joined.push_str(", ");
    joined.push_str(value.to_str().map_err(|e| anyhow!("invalid header value: {e}"))?);
  }
  Ok(Some(Cow::Owned(joined)))
}

/// Split a header value by a delimiter while respecting quoted substrings.
fn split_respecting_quotes(input: &str, delimiter: u8) -> Vec<&str> {
  let mut segments = Vec::new();
  let mut start = 0usize;
  let mut in_quotes = false;
  let mut escaped = false;
  for (idx, byte) in input.as_bytes().iter().copied().enumerate() {
    if escaped {
      escaped = false;
      continue;
    }
    match byte {
      b'\\' if in_quotes => escaped = true,
      b'"' => in_quotes = !in_quotes,
      b if b == delimiter && !in_quotes => {
        segments.push(input[start..idx].trim());
        start = idx + 1;
      }
      _ => {}
    }
  }
  segments.push(input[start..].trim());
  segments
}

/// Unquote a quoted-string value and unescape quoted-pair according to RFC 7230.
fn unquote_http_value(value: &str) -> Result<String> {
  let trimmed = value.trim();
  if !trimmed.starts_with('"') {
    return Ok(trimmed.to_string());
  }
  let Some(inner) = trimmed.strip_prefix('"').and_then(|s| s.strip_suffix('"')) else {
    return Err(anyhow!("unterminated quoted-string `{trimmed}`"));
  };
  let mut result = String::with_capacity(inner.len());
  let mut escaped = false;
  for ch in inner.chars() {
    if escaped {
      result.push(ch);
      escaped = false;
      continue;
    }
    if ch == '\\' {
      escaped = true;
      continue;
    }
    result.push(ch);
  }
  if escaped {
    return Err(anyhow!("unterminated escape sequence in quoted-string `{trimmed}`"));
  }
  Ok(result)
}

/// Parse a token in Forwarded header that is supposed to represent a client IP, which can be an IP address, "unknown", or obfuscated identifier.
fn parse_forwarded_ip_token(token: &str) -> Result<IpAddr> {
  match parse_forwarded_node(token)? {
    ForwardedNode { ip: Some(ip), .. } => Ok(ip),
    ForwardedNode { ip: None, .. } => Err(anyhow!("forwarded node `{token}` is not an IP address")),
  }
}

/// Parse the value of `for=` parameter in Forwarded header, which can be an IP address (with optional port), "unknown", or obfuscated identifier, according to RFC 7239.
fn parse_forwarded_node(token: &str) -> Result<ForwardedNode> {
  let trimmed = unquote_http_value(token)?;
  if trimmed.eq_ignore_ascii_case("unknown") {
    return Ok(ForwardedNode {
      ip: None,
      port: None,
      raw: ForwardedNodeRaw::Unknown,
    });
  }
  // RFC 7239 requires IPv6 literals with a port to be bracketed (e.g. `[2001:db8::1]:443`).
  // Applying rsplit_once(':') unconditionally would mis-parse an unbracketed IPv6 such as
  // `2001:db8::4711` as `ip=2001:db8::` + `port=4711`. So only split on ':' when the token
  // is bracketed, or when it contains exactly one ':' (IPv4 / unknown / obfuscated).
  if trimmed.starts_with('[') {
    if let Some((node, port)) = trimmed.rsplit_once(':') {
      if let Some(inner) = node.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
        let ip = canonicalize_ip(IpAddr::from_str(inner).map_err(|e| anyhow!("invalid forwarded address `{token}`: {e}"))?);
        return Ok(ForwardedNode {
          ip: Some(ip),
          port: Some(parse_forwarded_port(port, token)?.to_string()),
          raw: ForwardedNodeRaw::Ip,
        });
      }
    }
  } else if trimmed.matches(':').count() == 1 {
    if let Some((node, port)) = trimmed.rsplit_once(':') {
      if node.eq_ignore_ascii_case("unknown") {
        return Ok(ForwardedNode {
          ip: None,
          port: Some(port.to_string()),
          raw: ForwardedNodeRaw::Unknown,
        });
      }
      if node.starts_with('_') {
        return Ok(ForwardedNode {
          ip: None,
          port: Some(port.to_string()),
          raw: ForwardedNodeRaw::Obfuscated(node.to_string()),
        });
      }
      if let Ok(ip) = IpAddr::from_str(node) {
        return Ok(ForwardedNode {
          ip: Some(canonicalize_ip(ip)),
          port: Some(parse_forwarded_port(port, token)?.to_string()),
          raw: ForwardedNodeRaw::Ip,
        });
      }
    }
  }

  if let Some(inner) = trimmed.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
    let ip = IpAddr::from_str(inner).map_err(|e| anyhow!("invalid forwarded address `{token}`: {e}"))?;
    Ok(ForwardedNode {
      ip: Some(canonicalize_ip(ip)),
      port: None,
      raw: ForwardedNodeRaw::Ip,
    })
  } else if trimmed.starts_with('_') {
    Ok(ForwardedNode {
      ip: None,
      port: None,
      raw: ForwardedNodeRaw::Obfuscated(trimmed),
    })
  } else {
    let ip = IpAddr::from_str(&trimmed).map_err(|e| anyhow!("invalid forwarded address `{token}`: {e}"))?;
    Ok(ForwardedNode {
      ip: Some(canonicalize_ip(ip)),
      port: None,
      raw: ForwardedNodeRaw::Ip,
    })
  }
}

/// Parse the port part of `for=` parameter in Forwarded header, ensuring it is a valid u16.
fn parse_forwarded_port(port: &str, token: &str) -> Result<u16> {
  port
    .parse::<u16>()
    .map_err(|e| anyhow!("invalid forwarded port in `{token}`: {e}"))
}

/* --------------------------------------------------------------------------------------------------------- */
/* Chain helpers and output generation                                                                     */
/* --------------------------------------------------------------------------------------------------------- */

/// Canonicalize IP address to ensure consistent matching against trusted proxy list.
fn canonicalize_ip(ip: IpAddr) -> IpAddr {
  SocketAddr::new(ip, 0).to_canonical().ip()
}

/// Build a ForwardedEntry for the immediate peer, which represents this proxy's authoritative view of the client connection. This is used as the basis for forwarding chain normalization and generation.
fn build_peer_forwarded_entry(peer_ip: IpAddr, tls: bool, authoritative_host: Option<&str>) -> ForwardedEntry {
  ForwardedEntry {
    for_node: ForwardedNode {
      ip: Some(peer_ip),
      port: None,
      raw: ForwardedNodeRaw::Ip,
    },
    proto: if tls { Some("https".into()) } else { Some("http".into()) },
    host: authoritative_host.map(str::to_owned),
    by: None,
  }
}

/// Check if the given IP is in the list of trusted proxies.
fn is_trusted_proxy(ip: &IpAddr, trusted_forwarded_proxies: &[IpNet]) -> bool {
  let canonical = canonicalize_ip(*ip);
  trusted_forwarded_proxies.iter().any(|net| net.contains(&canonical))
}

/// Check if the given forwarding entry represents a trusted proxy hop that can be skipped in the forwarding chain. This is true if the `for` parameter is an IP address that is in the trusted proxies list.
fn entry_is_trusted_proxy(entry: &ForwardedEntry, trusted_forwarded_proxies: &[IpNet]) -> bool {
  entry
    .for_node
    .ip_addr()
    .map(|ip| is_trusted_proxy(&ip, trusted_forwarded_proxies))
    .unwrap_or(false)
}

/// Append `v4` to `out` as dotted-decimal, formatting each octet with `itoa` to bypass the
/// generic `core::fmt` integer path (`pad_integral`) that `Display` would otherwise route through.
fn push_ipv4(out: &mut String, v4: Ipv4Addr) {
  let mut buf = itoa::Buffer::new();
  let [a, b, c, d] = v4.octets();
  out.push_str(buf.format(a));
  out.push('.');
  out.push_str(buf.format(b));
  out.push('.');
  out.push_str(buf.format(c));
  out.push('.');
  out.push_str(buf.format(d));
}

/// Append an IP address to `out`. IPv4 takes the fast `itoa` path; IPv6 keeps the std formatter,
/// which already emits the RFC 5952 canonical (`::`-compressed) form.
fn push_ip_addr(out: &mut String, ip: &IpAddr) {
  match ip {
    IpAddr::V4(v4) => push_ipv4(out, *v4),
    IpAddr::V6(v6) => {
      let _ = write!(out, "{v6}");
    }
  }
}

/// Render the X-Forwarded-For value for a forwarding chain into a single comma-separated
/// buffer (no per-hop String), returning it together with the byte length of the first
/// element so the caller can slice out the X-Real-IP value without re-formatting.
/// Returns None if any entry in the chain is not an IP address, which indicates that we
/// cannot represent this chain in X-Forwarded-For and should fall back to a peer-only view.
/// An empty chain (impossible: normalization always yields at least the peer hop) is
/// reported as non-representable so the same fallback applies.
fn xff_csv_from_chain(chain: &[ForwardedEntry]) -> Option<(String, usize)> {
  if chain.is_empty() {
    return None;
  }
  let mut out = String::with_capacity(chain.len() * 16);
  let mut first_len = 0usize;
  for (idx, entry) in chain.iter().enumerate() {
    let ip = entry.for_node.ip_addr()?;
    if idx > 0 {
      out.push_str(", ");
    }
    push_ip_addr(&mut out, &ip);
    if idx == 0 {
      first_len = out.len();
    }
  }
  Some((out, first_len))
}

/// Generate an RFC 7239 `Forwarded` header from the normalized forwarding chain.
/// This function assumes that the forwarding chain is present and well-formed.
/// Each hop is emitted with a `for=` parameter, and may additionally include
/// `proto=`, `host=`, and `by=` parameters when those fields are present.
/// All hops are written into one shared buffer (no per-hop Vec<String> + join).
pub(super) fn generate_forwarded_header(normalized_forwarding_chain: &[ForwardedEntry]) -> Result<String> {
  if normalized_forwarding_chain.is_empty() {
    return Err(anyhow!("No forwarding chain found for Forwarded generation"));
  }

  // for= is always present. proto=, host=, and by= might not be present.
  let mut out = String::with_capacity(normalized_forwarding_chain.len() * 24);
  for (idx, entry) in normalized_forwarding_chain.iter().enumerate() {
    if idx > 0 {
      out.push_str(", ");
    }
    out.push_str("for=");
    write_forwarded_node(&mut out, &entry.for_node)?;
    if let Some(proto) = &entry.proto {
      out.push_str(";proto=");
      write_forwarded_param_value(&mut out, proto);
    }
    if let Some(host) = &entry.host {
      out.push_str(";host=");
      write_forwarded_param_value(&mut out, host);
    }
    if let Some(by) = &entry.by {
      out.push_str(";by=");
      write_forwarded_param_value(&mut out, by);
    }
  }
  Ok(out)
}

/// Return true if `c` is an RFC 7230 tchar, i.e. may appear unquoted in a token.
fn is_tchar(c: char) -> bool {
  matches!(
    c,
    '!' | '#' | '$' | '%' | '&' | '\'' | '*' | '+' | '-' | '.' | '^' | '_' | '`' | '|' | '~'
  ) || c.is_ascii_alphanumeric()
}

/// Write a Forwarded parameter value (proto/host/by) into `out`. If the value contains any
/// non-tchar byte (e.g. `:` for ports, `[`/`]` for IPv6 literals), wrap it in a
/// quoted-string and escape `\` and `"` as RFC 7230 quoted-pair. Otherwise emit as-is.
fn write_forwarded_param_value(out: &mut String, value: &str) {
  if !value.is_empty() && value.chars().all(is_tchar) {
    out.push_str(value);
    return;
  }
  out.reserve(value.len() + 2);
  out.push('"');
  for ch in value.chars() {
    if ch == '\\' || ch == '"' {
      out.push('\\');
    }
    out.push(ch);
  }
  out.push('"');
}

/// Write the for= value in Forwarded header into `out` according to RFC 7239, which may
/// require quoting and bracketing for IPv6 addresses.
fn write_forwarded_node(out: &mut String, node: &ForwardedNode) -> Result<()> {
  // Writing into a String is infallible; IPv4 uses the fast itoa path, the rest keep std fmt.
  match (&node.raw, node.ip, node.port.as_deref()) {
    (ForwardedNodeRaw::Ip, Some(IpAddr::V4(v4)), None) => push_ipv4(out, v4),
    (ForwardedNodeRaw::Ip, Some(IpAddr::V4(v4)), Some(port)) => {
      out.push('"');
      push_ipv4(out, v4);
      out.push(':');
      out.push_str(port);
      out.push('"');
    }
    (ForwardedNodeRaw::Ip, Some(IpAddr::V6(v6)), None) => {
      let _ = write!(out, "\"[{v6}]\"");
    }
    (ForwardedNodeRaw::Ip, Some(IpAddr::V6(v6)), Some(port)) => {
      let _ = write!(out, "\"[{v6}]:{port}\"");
    }
    (ForwardedNodeRaw::Unknown, None, None) => out.push_str("unknown"),
    (ForwardedNodeRaw::Unknown, None, Some(port)) => {
      let _ = write!(out, "\"unknown:{port}\"");
    }
    (ForwardedNodeRaw::Obfuscated(node), None, None) => out.push_str(node),
    (ForwardedNodeRaw::Obfuscated(node), None, Some(port)) => {
      let _ = write!(out, "\"{node}:{port}\"");
    }
    _ => return Err(anyhow!("invalid forwarded node state")),
  }
  Ok(())
}

/* -------------------------------------------------------------------------------------------------- */
/* Client-visible scheme detection (used by sticky-cookie Secure attribute                            */
/* -------------------------------------------------------------------------------------------------- */

/// Decide whether the request's client-visible scheme is HTTPS, for the purpose of
/// setting the `Secure` attribute on response Set-Cookie values.
///
/// 1. If the rpxy listener is TLS-terminating, return true.
/// 2. Otherwise, only honor forwarding-derived scheme when the immediate peer is in
///    `trusted_forwarded_proxies` (same trust boundary as the forwarding-header policy).
/// 3. Header priority: `X-Forwarded-Proto` first comma-element wins; fall back to the
///    `proto=` parameter of the first `Forwarded` entry.
/// 4. Any parse failure fails closed to false (debug-logged, not warn-logged) and does
///    NOT fall through to the lower-priority source — a malformed `X-Forwarded-Proto`
///    short-circuits without consulting `Forwarded`.
#[cfg(feature = "sticky-cookie")]
pub(in crate::message_handler) fn client_visible_secure(
  tls_enabled: bool,
  client_addr: &SocketAddr,
  headers: &HeaderMap,
  trusted_forwarded_proxies: &[IpNet],
) -> bool {
  if tls_enabled {
    return true;
  }
  let peer_ip = canonicalize_ip(client_addr.to_canonical().ip());
  if !is_trusted_proxy(&peer_ip, trusted_forwarded_proxies) {
    return false;
  }
  let scheme = match xforwarded_proto_first(headers) {
    Err(()) => return false, // XFP parse failure: fail closed, do NOT fall through
    Ok(Some(s)) => Some(s),
    Ok(None) => match forwarded_first_proto(headers) {
      Err(()) => return false, // Forwarded parse failure: fail closed
      Ok(s) => s,
    },
  };
  scheme.is_some_and(|s| s.eq_ignore_ascii_case("https"))
}

/// Read the first comma-separated element of `X-Forwarded-Proto`.
///
/// Returns:
/// - `Ok(Some(scheme))` when the header is present and the first element is non-empty.
/// - `Ok(None)` when the header is absent or its first element is empty after trimming
///   (caller may fall back to a lower-priority source).
/// - `Err(())` when the header is present but unreadable (non-UTF-8 etc.). Caller MUST
///   NOT fall back; doing so would let a malformed XFP enable a low-priority `Forwarded:
///   proto=https` to elevate `Secure`.
#[cfg(feature = "sticky-cookie")]
fn xforwarded_proto_first(headers: &HeaderMap) -> Result<Option<String>, ()> {
  let raw = match join_header_values(headers, X_FORWARDED_PROTO) {
    Ok(Some(v)) => v,
    Ok(None) => return Ok(None),
    Err(e) => {
      debug!("X-Forwarded-Proto header value not readable: {e}");
      return Err(());
    }
  };
  let first = raw.split(',').next().unwrap_or("").trim();
  if first.is_empty() {
    Ok(None)
  } else {
    Ok(Some(first.to_string()))
  }
}

/// Read the `proto=` parameter of the first entry of the `Forwarded` header, if present.
///
/// Distinct from `parse_forwarded_header_entry`: this helper does not require a `for=`
/// parameter, since for `Secure` decisions only the scheme matters.
///
/// Returns:
/// - `Ok(Some(scheme))` when the first entry has a non-empty, well-formed `proto=` value.
/// - `Ok(None)` when the header is absent, the first entry has no `proto=`, or the value
///   is empty.
/// - `Err(())` on header value / quoted-string parse failure (fail-closed signal).
#[cfg(feature = "sticky-cookie")]
fn forwarded_first_proto(headers: &HeaderMap) -> Result<Option<String>, ()> {
  let raw = match join_header_values(headers, header::FORWARDED) {
    Ok(Some(v)) => v,
    Ok(None) => return Ok(None),
    Err(e) => {
      debug!("Forwarded header value not readable: {e}");
      return Err(());
    }
  };
  let Some(first_entry) = split_respecting_quotes(&raw, b',').into_iter().find(|e| !e.is_empty()) else {
    return Ok(None);
  };
  for param in split_respecting_quotes(first_entry, b';')
    .into_iter()
    .filter(|p| !p.is_empty())
  {
    let Some((key, value)) = param.split_once('=') else {
      continue;
    };
    if !key.trim().eq_ignore_ascii_case("proto") {
      continue;
    }
    return match unquote_http_value(value.trim()) {
      Ok(v) if !v.is_empty() => Ok(Some(v)),
      Ok(_) => Ok(None),
      Err(e) => {
        debug!("Forwarded proto= unquote failure: {e}");
        Err(())
      }
    };
  }
  Ok(None)
}

#[cfg(test)]
mod tests {
  use super::{super::common::host_from_uri_or_host_header, *};
  use std::borrow::Cow;

  fn trusted(cidrs: &[&str]) -> Vec<IpNet> {
    cidrs.iter().map(|c| c.parse::<IpNet>().unwrap()).collect()
  }

  #[test]
  fn join_header_values_single_field_line_borrows() {
    let mut headers = HeaderMap::new();
    headers.append(X_FORWARDED_FOR, HeaderValue::from_static("1.2.3.4, 5.6.7.8"));
    let value = join_header_values(&headers, X_FORWARDED_FOR).unwrap().unwrap();
    assert!(matches!(value, Cow::Borrowed(_)), "a single field-line must be borrowed");
    assert_eq!(value, "1.2.3.4, 5.6.7.8");
  }

  #[test]
  fn join_header_values_multiple_field_lines_join() {
    let mut headers = HeaderMap::new();
    headers.append(X_FORWARDED_FOR, HeaderValue::from_static("1.2.3.4"));
    headers.append(X_FORWARDED_FOR, HeaderValue::from_static("5.6.7.8"));
    let value = join_header_values(&headers, X_FORWARDED_FOR).unwrap().unwrap();
    assert!(matches!(value, Cow::Owned(_)), "multiple field-lines must be joined");
    assert_eq!(value, "1.2.3.4, 5.6.7.8");
  }

  #[test]
  fn join_header_values_errors_when_a_non_first_line_is_unreadable() {
    // Fail-closed: an unreadable value after the first field-line must still error, so a malformed
    // later line cannot be silently dropped. Feature-independent guard for the proto readers.
    let mut headers = HeaderMap::new();
    headers.append(X_FORWARDED_FOR, HeaderValue::from_static("1.2.3.4"));
    headers.append(X_FORWARDED_FOR, HeaderValue::from_bytes(b"\xff").unwrap());
    assert!(join_header_values(&headers, X_FORWARDED_FOR).is_err());
  }

  #[test]
  fn push_ip_addr_matches_std_display() {
    // The itoa-based writer must be byte-identical to std Display across IPv4 octet boundaries,
    // and must defer to std (RFC 5952 canonical) formatting for IPv6.
    for s in [
      "0.0.0.0",
      "1.2.3.4",
      "9.10.99.100",
      "127.0.0.1",
      "192.168.0.255",
      "255.255.255.255",
    ] {
      let ip: IpAddr = s.parse().unwrap();
      let mut out = String::new();
      push_ip_addr(&mut out, &ip);
      assert_eq!(out, ip.to_string(), "v4 {s}");
    }
    for s in ["::", "::1", "2001:db8::1", "2001:db8:0:0:1:0:0:1", "::ffff:1.2.3.4"] {
      let ip: IpAddr = s.parse().unwrap();
      let mut out = String::new();
      push_ip_addr(&mut out, &ip);
      assert_eq!(out, ip.to_string(), "v6 {s}");
    }
  }

  /// Test shim mirroring the production call path: the authoritative host is computed once
  /// from the original URI + Host header (exactly as `generate_request_forwarded` does,
  /// before any header mutation) and handed to `add_forwarding_header`.
  fn add_forwarding_header_from_original(
    headers: &mut HeaderMap,
    client_addr: &SocketAddr,
    listen_addr: &SocketAddr,
    tls: bool,
    original_uri: &Uri,
    trusted_forwarded_proxies: &[IpNet],
  ) -> Result<()> {
    let authoritative_host = host_from_uri_or_host_header(original_uri, headers.get(header::HOST))
      .ok()
      .map(Cow::into_owned);
    add_forwarding_header(
      headers,
      client_addr,
      listen_addr,
      tls,
      original_uri,
      authoritative_host.as_deref(),
      trusted_forwarded_proxies,
    )
  }

  #[test]
  fn untrusted_peer_ignores_incoming_forwarding_headers() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));
    headers.insert(X_FORWARDED_FOR, HeaderValue::from_static("1.2.3.4"));
    headers.insert(X_FORWARDED_PROTO, HeaderValue::from_static("https"));
    headers.insert(X_FORWARDED_PORT, HeaderValue::from_static("443"));
    headers.insert(X_FORWARDED_HOST, HeaderValue::from_static("spoofed.example"));
    headers.insert(
      header::FORWARDED,
      HeaderValue::from_static("for=1.2.3.4;proto=https;host=app.example"),
    );

    add_forwarding_header_from_original(
      &mut headers,
      &"203.0.113.10:4321".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/demo?q=1"),
      &[],
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "203.0.113.10");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "203.0.113.10");
    assert_eq!(headers.get(X_FORWARDED_PROTO).unwrap(), "http");
    assert_eq!(headers.get(X_FORWARDED_PORT).unwrap(), "8080");
    assert_eq!(headers.get(X_FORWARDED_HOST).unwrap(), "app.example");
    assert_eq!(
      headers.get(header::FORWARDED).unwrap(),
      "for=203.0.113.10;proto=http;host=app.example"
    );
  }

  /// Pin X-Forwarded-Host for every authoritative-host source: URI with port, URI without
  /// port, Host-header fallback, and removal when no host exists anywhere.
  #[test]
  fn x_forwarded_host_reflects_authoritative_host() {
    let client = "203.0.113.10:4321".parse().unwrap();
    let listen = "192.0.2.1:8080".parse().unwrap();

    // URI host with explicit port wins, port preserved
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("ignored.example"));
    add_forwarding_header_from_original(&mut headers, &client, &listen, false, &Uri::from_static("https://app.example:8443/p"), &[]).unwrap();
    assert_eq!(headers.get(X_FORWARDED_HOST).unwrap(), "app.example:8443");

    // URI host without port
    let mut headers = HeaderMap::new();
    add_forwarding_header_from_original(&mut headers, &client, &listen, false, &Uri::from_static("https://app.example/p"), &[]).unwrap();
    assert_eq!(headers.get(X_FORWARDED_HOST).unwrap(), "app.example");

    // relative URI falls back to the Host header, ports preserved
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("fallback.example:8080"));
    add_forwarding_header_from_original(&mut headers, &client, &listen, false, &Uri::from_static("/p"), &[]).unwrap();
    assert_eq!(headers.get(X_FORWARDED_HOST).unwrap(), "fallback.example:8080");

    // no host anywhere: a pre-set (spoofed) X-Forwarded-Host is removed
    let mut headers = HeaderMap::new();
    headers.insert(X_FORWARDED_HOST, HeaderValue::from_static("spoofed.example"));
    add_forwarding_header_from_original(&mut headers, &client, &listen, false, &Uri::from_static("/p"), &[]).unwrap();
    assert!(headers.get(X_FORWARDED_HOST).is_none());
  }

  #[test]
  fn trusted_proxy_keeps_verified_trusted_suffix() {
    let mut headers = HeaderMap::new();
    headers.insert(X_FORWARDED_FOR, HeaderValue::from_static("198.51.100.10, 10.9.0.4"));

    add_forwarding_header_from_original(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8443".parse().unwrap(),
      true,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "198.51.100.10, 10.9.0.4, 10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "198.51.100.10");
    assert_eq!(headers.get(X_FORWARDED_PROTO).unwrap(), "https");
  }

  #[test]
  fn trusted_proxy_stops_at_last_non_trusted_hop() {
    let mut headers = HeaderMap::new();
    headers.insert(X_FORWARDED_FOR, HeaderValue::from_static("198.51.100.10, 203.0.113.20"));

    add_forwarding_header_from_original(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "203.0.113.20, 10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "203.0.113.20");
  }

  #[test]
  fn trusted_proxy_uses_forwarded_when_xff_missing() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));
    headers.insert(header::FORWARDED, HeaderValue::from_static("for=198.51.100.10, for=10.9.0.4"));

    add_forwarding_header_from_original(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "198.51.100.10, 10.9.0.4, 10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "198.51.100.10");
    assert_eq!(
      headers.get(header::FORWARDED).unwrap(),
      "for=198.51.100.10, for=10.9.0.4, for=10.1.2.3;proto=http;host=app.example"
    );
  }

  #[test]
  fn trusted_proxy_falls_back_to_xff_when_forwarded_chain_is_inconsistent() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));
    headers.insert(X_FORWARDED_FOR, HeaderValue::from_static("198.51.100.10"));
    headers.insert(
      header::FORWARDED,
      HeaderValue::from_static("for=203.0.113.20;proto=https;host=app.example"),
    );

    add_forwarding_header_from_original(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "198.51.100.10, 10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "198.51.100.10");
    assert_eq!(
      headers.get(header::FORWARDED).unwrap(),
      "for=198.51.100.10, for=10.1.2.3;proto=http;host=app.example"
    );
  }

  #[test]
  fn trusted_proxy_accepts_multiple_xff_field_lines() {
    let mut headers = HeaderMap::new();
    headers.append(X_FORWARDED_FOR, HeaderValue::from_static("198.51.100.10"));
    headers.append(X_FORWARDED_FOR, HeaderValue::from_static("10.9.0.4"));

    add_forwarding_header_from_original(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "198.51.100.10, 10.9.0.4, 10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "198.51.100.10");
  }

  #[test]
  fn trusted_proxy_accepts_multiple_forwarded_field_lines() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));
    headers.append(header::FORWARDED, HeaderValue::from_static("for=198.51.100.10"));
    headers.append(header::FORWARDED, HeaderValue::from_static("for=10.9.0.4"));

    add_forwarding_header_from_original(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "198.51.100.10, 10.9.0.4, 10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "198.51.100.10");
    assert_eq!(
      headers.get(header::FORWARDED).unwrap(),
      "for=198.51.100.10, for=10.9.0.4, for=10.1.2.3;proto=http;host=app.example"
    );
  }

  #[test]
  fn ipv6_peer_produces_correctly_formatted_headers() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));

    add_forwarding_header_from_original(
      &mut headers,
      &"[2001:db8::1]:4321".parse().unwrap(),
      &"[::1]:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &[],
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "2001:db8::1");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "2001:db8::1");
    assert_eq!(headers.get(X_FORWARDED_HOST).unwrap(), "app.example");
    assert!(!headers.contains_key(header::FORWARDED));
  }

  #[test]
  fn x_forwarded_host_uses_uri_authority_for_absolute_form() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("host-header.example"));
    headers.insert(X_FORWARDED_HOST, HeaderValue::from_static("spoofed.example"));

    add_forwarding_header_from_original(
      &mut headers,
      &"203.0.113.10:4321".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &"http://uri-authority.example:8080/demo?q=1".parse::<Uri>().unwrap(),
      &[],
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_HOST).unwrap(), "uri-authority.example:8080");
  }

  #[test]
  fn x_forwarded_host_is_cleared_when_original_host_is_unavailable() {
    let mut headers = HeaderMap::new();
    headers.insert(X_FORWARDED_HOST, HeaderValue::from_static("spoofed.example"));

    add_forwarding_header_from_original(
      &mut headers,
      &"203.0.113.10:4321".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/demo?q=1"),
      &[],
    )
    .unwrap();

    assert!(headers.get(X_FORWARDED_HOST).is_none());
  }

  #[test]
  fn generate_forwarded_header_quotes_bracketed_ipv6_for_node() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));

    add_forwarding_header_from_original(
      &mut headers,
      &"[2001:db8::1]:4321".parse().unwrap(),
      &"[::1]:8080".parse().unwrap(),
      true,
      &Uri::from_static("/"),
      &[],
    )
    .unwrap();

    let normalized_chain = vec![ForwardedEntry {
      for_node: ForwardedNode {
        ip: Some("2001:db8::1".parse().unwrap()),
        port: None,
        raw: ForwardedNodeRaw::Ip,
      },
      proto: Some("https".into()),
      host: Some("app.example".into()),
      by: None,
    }];
    let forwarded = generate_forwarded_header(&normalized_chain).unwrap();
    assert_eq!(forwarded, "for=\"[2001:db8::1]\";proto=https;host=app.example");
  }

  #[test]
  fn ipv4_mapped_ipv6_peer_is_canonicalized() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));

    // ::ffff:10.1.2.3 should be canonicalized to 10.1.2.3
    add_forwarding_header_from_original(
      &mut headers,
      &"[::ffff:10.1.2.3]:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &[],
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "10.1.2.3");
  }

  #[test]
  fn ipv4_mapped_ipv6_matches_trusted_v4_cidr() {
    let mut headers = HeaderMap::new();
    headers.insert(X_FORWARDED_FOR, HeaderValue::from_static("198.51.100.10"));

    // Peer is ::ffff:10.1.2.3, trusted CIDR is 10.0.0.0/8 (IPv4)
    add_forwarding_header_from_original(
      &mut headers,
      &"[::ffff:10.1.2.3]:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "198.51.100.10, 10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "198.51.100.10");
  }

  #[test]
  fn trusted_proxy_parses_forwarded_with_ipv6() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));
    headers.insert(
      header::FORWARDED,
      HeaderValue::from_static("for=\"[2001:db8::1]\";proto=https;host=app.example"),
    );

    add_forwarding_header_from_original(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "2001:db8::1, 10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "2001:db8::1");
  }

  #[test]
  fn xff_with_empty_segments_assigns_proto_to_last_valid_entry() {
    let mut headers = HeaderMap::new();
    headers.insert(X_FORWARDED_FOR, HeaderValue::from_static("198.51.100.10, , 203.0.113.20"));
    headers.insert(X_FORWARDED_PROTO, HeaderValue::from_static("https"));

    add_forwarding_header_from_original(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    // proto should be assigned to 203.0.113.20 (the last valid entry), not lost
    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "203.0.113.20, 10.1.2.3");
  }

  #[test]
  fn trusted_proxy_accepts_forwarded_with_port() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));
    headers.insert(
      header::FORWARDED,
      HeaderValue::from_static("for=\"192.0.2.43:4711\", for=10.9.0.4"),
    );

    add_forwarding_header_from_original(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "192.0.2.43, 10.9.0.4, 10.1.2.3");
    assert_eq!(
      headers.get(header::FORWARDED).unwrap(),
      "for=\"192.0.2.43:4711\", for=10.9.0.4, for=10.1.2.3;proto=http;host=app.example"
    );
  }

  #[test]
  fn trusted_proxy_with_forwarded_unknown_falls_back_to_peer_only() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));
    headers.insert(header::FORWARDED, HeaderValue::from_static("for=unknown, for=10.9.0.4"));

    add_forwarding_header_from_original(
      &mut headers,
      &"10.1.2.3:1234".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &trusted(&["10.0.0.0/8"]),
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_FOR).unwrap(), "10.1.2.3");
    assert_eq!(headers.get(X_REAL_IP).unwrap(), "10.1.2.3");
    assert_eq!(
      headers.get(header::FORWARDED).unwrap(),
      "for=10.1.2.3;proto=http;host=app.example"
    );
  }

  #[test]
  fn parse_forwarded_node_accepts_unbracketed_ipv6_without_port() {
    // An unbracketed IPv6 literal must not be mis-parsed as `ip + :port`:
    // the trailing `::4711` is a valid hextet, not a port.
    let node = parse_forwarded_node("2001:db8::4711").unwrap();
    assert_eq!(node.ip, Some("2001:db8::4711".parse::<IpAddr>().unwrap()));
    assert_eq!(node.port, None);
    assert_eq!(node.raw, ForwardedNodeRaw::Ip);
  }

  #[test]
  fn parse_forwarded_node_accepts_bracketed_ipv6_with_port() {
    // RFC 7239 requires IPv6 addresses with a port to be bracketed.
    let node = parse_forwarded_node("\"[2001:db8::1]:443\"").unwrap();
    assert_eq!(node.ip, Some("2001:db8::1".parse::<IpAddr>().unwrap()));
    assert_eq!(node.port.as_deref(), Some("443"));
    assert_eq!(node.raw, ForwardedNodeRaw::Ip);
  }

  #[test]
  fn parse_forwarded_node_rejects_unbracketed_ipv6_with_port() {
    // Without brackets, the trailing colon-number must not be treated as a port.
    // `2001:db8::1:443` is itself a valid IPv6 literal and should parse as such.
    let node = parse_forwarded_node("2001:db8::1:443").unwrap();
    assert_eq!(node.ip, Some("2001:db8::1:443".parse::<IpAddr>().unwrap()));
    assert_eq!(node.port, None);
  }

  #[test]
  fn parse_forwarded_node_still_parses_ipv4_with_port() {
    let node = parse_forwarded_node("192.0.2.1:443").unwrap();
    assert_eq!(node.ip, Some("192.0.2.1".parse::<IpAddr>().unwrap()));
    assert_eq!(node.port.as_deref(), Some("443"));
  }

  /// Test shim: render a single Forwarded parameter value through the writer helper,
  /// so each assertion below stays a single expression. Expected bytes are unchanged
  /// from the pre-writer `format_forwarded_param_value` implementation.
  fn fmt_param(value: &str) -> String {
    let mut out = String::new();
    write_forwarded_param_value(&mut out, value);
    out
  }

  #[test]
  fn format_forwarded_param_value_leaves_token_unquoted() {
    assert_eq!(fmt_param("https"), "https");
    assert_eq!(fmt_param("example.com"), "example.com");
  }

  #[test]
  fn format_forwarded_param_value_quotes_host_with_port() {
    // `:` is not a tchar, so `host=example.com:8443` must be emitted as quoted-string.
    assert_eq!(fmt_param("example.com:8443"), "\"example.com:8443\"");
  }

  #[test]
  fn format_forwarded_param_value_quotes_ipv6_literal() {
    assert_eq!(fmt_param("[2001:db8::1]"), "\"[2001:db8::1]\"");
  }

  #[test]
  fn format_forwarded_param_value_escapes_quote_and_backslash() {
    assert_eq!(fmt_param("a\"b\\c"), "\"a\\\"b\\\\c\"");
  }

  /// Pin the writer rewrite of generate_forwarded_header against the rare for= node arms
  /// (unknown / obfuscated, with and without port) and a quoted-pair host in one chain.
  #[test]
  fn generate_forwarded_header_rare_node_arms() {
    let ip_node = |ip: &str, port: Option<&str>| ForwardedNode {
      ip: Some(ip.parse().unwrap()),
      port: port.map(str::to_owned),
      raw: ForwardedNodeRaw::Ip,
    };
    let raw_node = |raw: ForwardedNodeRaw, port: Option<&str>| ForwardedNode {
      ip: None,
      port: port.map(str::to_owned),
      raw,
    };
    let entry = |for_node: ForwardedNode, host: Option<&str>| ForwardedEntry {
      for_node,
      proto: None,
      host: host.map(str::to_owned),
      by: None,
    };

    let chain = vec![
      entry(raw_node(ForwardedNodeRaw::Unknown, None), None),
      entry(raw_node(ForwardedNodeRaw::Unknown, Some("8080")), None),
      entry(raw_node(ForwardedNodeRaw::Obfuscated("_hidden".to_owned()), None), None),
      entry(raw_node(ForwardedNodeRaw::Obfuscated("_hidden".to_owned()), Some("8081")), None),
      entry(ip_node("203.0.113.5", Some("7070")), None),
      entry(ip_node("203.0.113.6", None), Some("a\"b\\c")),
    ];

    assert_eq!(
      generate_forwarded_header(&chain).unwrap(),
      "for=unknown, for=\"unknown:8080\", for=_hidden, for=\"_hidden:8081\", for=\"203.0.113.5:7070\", for=203.0.113.6;host=\"a\\\"b\\\\c\""
    );
  }

  /// Pin xff_csv_from_chain: CSV bytes, first-element length, and the non-representable cases.
  #[test]
  fn xff_csv_from_chain_renders_csv_and_first_element() {
    let ip_entry = |ip: &str| ForwardedEntry {
      for_node: ForwardedNode {
        ip: Some(ip.parse().unwrap()),
        port: None,
        raw: ForwardedNodeRaw::Ip,
      },
      proto: None,
      host: None,
      by: None,
    };

    let (csv, first_len) = xff_csv_from_chain(&[ip_entry("198.51.100.10"), ip_entry("2001:db8::1"), ip_entry("10.0.0.4")]).unwrap();
    assert_eq!(csv, "198.51.100.10, 2001:db8::1, 10.0.0.4");
    assert_eq!(&csv[..first_len], "198.51.100.10");

    let (csv, first_len) = xff_csv_from_chain(&[ip_entry("198.51.100.10")]).unwrap();
    assert_eq!(&csv[..first_len], csv.as_str());

    // a non-IP hop or an empty chain cannot be represented in X-Forwarded-For
    let unknown = ForwardedEntry {
      for_node: ForwardedNode {
        ip: None,
        port: None,
        raw: ForwardedNodeRaw::Unknown,
      },
      proto: None,
      host: None,
      by: None,
    };
    assert!(xff_csv_from_chain(&[ip_entry("198.51.100.10"), unknown]).is_none());
    assert!(xff_csv_from_chain(&[]).is_none());
  }

  #[test]
  fn generate_forwarded_header_quotes_host_with_port() {
    let chain = vec![ForwardedEntry {
      for_node: ForwardedNode {
        ip: Some("192.0.2.1".parse().unwrap()),
        port: None,
        raw: ForwardedNodeRaw::Ip,
      },
      proto: Some("https".into()),
      host: Some("example.com:8443".into()),
      by: None,
    }];
    assert_eq!(
      generate_forwarded_header(&chain).unwrap(),
      "for=192.0.2.1;proto=https;host=\"example.com:8443\""
    );
  }

  #[test]
  fn constant_overwrite_headers_are_byte_identical_non_tls() {
    // Guards the HeaderValue::from_static / from(u16) overwrites against accidental drift:
    // the constant downstream-view headers must keep their exact byte values.
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));

    add_forwarding_header_from_original(
      &mut headers,
      &"203.0.113.10:4321".parse().unwrap(),
      &"192.0.2.1:8080".parse().unwrap(),
      false,
      &Uri::from_static("/"),
      &[],
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_PROTO).unwrap(), "http");
    assert_eq!(headers.get(X_FORWARDED_PORT).unwrap(), "8080");
    assert_eq!(headers.get(X_FORWARDED_SSL).unwrap(), "off");
    assert_eq!(headers.get(PROXY).unwrap(), "");
  }

  #[test]
  fn constant_overwrite_headers_are_byte_identical_tls() {
    let mut headers = HeaderMap::new();
    headers.insert(header::HOST, HeaderValue::from_static("app.example"));

    add_forwarding_header_from_original(
      &mut headers,
      &"203.0.113.10:4321".parse().unwrap(),
      &"192.0.2.1:8443".parse().unwrap(),
      true,
      &Uri::from_static("/"),
      &[],
    )
    .unwrap();

    assert_eq!(headers.get(X_FORWARDED_PROTO).unwrap(), "https");
    assert_eq!(headers.get(X_FORWARDED_PORT).unwrap(), "8443");
    assert_eq!(headers.get(X_FORWARDED_SSL).unwrap(), "on");
    assert_eq!(headers.get(PROXY).unwrap(), "");
  }

  /* ---------------------- client_visible_secure ---------------------- */

  #[cfg(feature = "sticky-cookie")]
  fn untrusted_addr() -> SocketAddr {
    "203.0.113.10:4321".parse().unwrap()
  }

  #[cfg(feature = "sticky-cookie")]
  fn trusted_addr() -> SocketAddr {
    "10.1.2.3:1234".parse().unwrap()
  }

  #[cfg(feature = "sticky-cookie")]
  fn cidr_10() -> Vec<IpNet> {
    trusted(&["10.0.0.0/8"])
  }

  #[cfg(feature = "sticky-cookie")]
  #[test]
  fn cvs_tls_enabled_returns_true_regardless() {
    let mut headers = HeaderMap::new();
    headers.insert(X_FORWARDED_PROTO, HeaderValue::from_static("http"));
    headers.insert(header::FORWARDED, HeaderValue::from_static("proto=http"));
    assert!(client_visible_secure(true, &untrusted_addr(), &headers, &[]));
    assert!(client_visible_secure(true, &trusted_addr(), &headers, &cidr_10()));
  }

  #[cfg(feature = "sticky-cookie")]
  #[test]
  fn cvs_untrusted_peer_ignores_xfp_https() {
    let mut headers = HeaderMap::new();
    headers.insert(X_FORWARDED_PROTO, HeaderValue::from_static("https"));
    assert!(!client_visible_secure(false, &untrusted_addr(), &headers, &cidr_10()));
  }

  #[cfg(feature = "sticky-cookie")]
  #[test]
  fn cvs_trusted_peer_xfp_https_returns_true() {
    let mut headers = HeaderMap::new();
    headers.insert(X_FORWARDED_PROTO, HeaderValue::from_static("https"));
    assert!(client_visible_secure(false, &trusted_addr(), &headers, &cidr_10()));
  }

  #[cfg(feature = "sticky-cookie")]
  #[test]
  fn cvs_trusted_peer_forwarded_proto_https_no_for() {
    let mut headers = HeaderMap::new();
    headers.insert(header::FORWARDED, HeaderValue::from_static("proto=https"));
    assert!(client_visible_secure(false, &trusted_addr(), &headers, &cidr_10()));
  }

  #[cfg(feature = "sticky-cookie")]
  #[test]
  fn cvs_trusted_peer_xfp_http_returns_false() {
    let mut headers = HeaderMap::new();
    headers.insert(X_FORWARDED_PROTO, HeaderValue::from_static("http"));
    assert!(!client_visible_secure(false, &trusted_addr(), &headers, &cidr_10()));
  }

  #[cfg(feature = "sticky-cookie")]
  #[test]
  fn cvs_trusted_peer_no_proto_header_returns_false() {
    let headers = HeaderMap::new();
    assert!(!client_visible_secure(false, &trusted_addr(), &headers, &cidr_10()));
  }

  #[cfg(feature = "sticky-cookie")]
  #[test]
  fn cvs_xfp_multi_hop_first_wins() {
    let mut headers = HeaderMap::new();
    headers.insert(X_FORWARDED_PROTO, HeaderValue::from_static("https, http"));
    assert!(client_visible_secure(false, &trusted_addr(), &headers, &cidr_10()));

    let mut headers2 = HeaderMap::new();
    headers2.insert(X_FORWARDED_PROTO, HeaderValue::from_static("http, https"));
    assert!(!client_visible_secure(false, &trusted_addr(), &headers2, &cidr_10()));
  }

  #[cfg(feature = "sticky-cookie")]
  #[test]
  fn cvs_conflict_xfp_wins() {
    let mut headers = HeaderMap::new();
    headers.insert(X_FORWARDED_PROTO, HeaderValue::from_static("https"));
    headers.insert(header::FORWARDED, HeaderValue::from_static("for=1.2.3.4;proto=http"));
    assert!(client_visible_secure(false, &trusted_addr(), &headers, &cidr_10()));
  }

  #[cfg(feature = "sticky-cookie")]
  #[test]
  fn cvs_conflict_inverse_xfp_wins() {
    let mut headers = HeaderMap::new();
    headers.insert(X_FORWARDED_PROTO, HeaderValue::from_static("http"));
    headers.insert(header::FORWARDED, HeaderValue::from_static("for=1.2.3.4;proto=https"));
    assert!(!client_visible_secure(false, &trusted_addr(), &headers, &cidr_10()));
  }

  #[cfg(feature = "sticky-cookie")]
  #[test]
  fn cvs_malformed_forwarded_fails_closed() {
    let mut headers = HeaderMap::new();
    headers.insert(header::FORWARDED, HeaderValue::from_static("proto=\"https"));
    assert!(!client_visible_secure(false, &trusted_addr(), &headers, &cidr_10()));
  }

  #[cfg(feature = "sticky-cookie")]
  #[test]
  fn cvs_non_utf8_xfp_fails_closed() {
    let mut headers = HeaderMap::new();
    headers.insert(
      X_FORWARDED_PROTO,
      HeaderValue::from_bytes(b"\xffhttps").expect("HeaderValue accepts non-UTF-8 bytes"),
    );
    assert!(!client_visible_secure(false, &trusted_addr(), &headers, &cidr_10()));
  }

  #[cfg(feature = "sticky-cookie")]
  #[test]
  fn cvs_empty_xfp_falls_through_to_forwarded() {
    let mut headers = HeaderMap::new();
    headers.insert(X_FORWARDED_PROTO, HeaderValue::from_static(""));
    headers.insert(header::FORWARDED, HeaderValue::from_static("proto=https"));
    assert!(client_visible_secure(false, &trusted_addr(), &headers, &cidr_10()));
  }

  #[cfg(feature = "sticky-cookie")]
  #[test]
  fn cvs_malformed_xfp_does_not_fall_through_to_forwarded_https() {
    // Malformed (non-UTF-8) X-Forwarded-Proto must short-circuit to fail-closed,
    // even when a valid Forwarded: proto=https is present at the lower priority.
    let mut headers = HeaderMap::new();
    headers.insert(
      X_FORWARDED_PROTO,
      HeaderValue::from_bytes(b"\xffhttps").expect("HeaderValue accepts non-UTF-8 bytes"),
    );
    headers.insert(header::FORWARDED, HeaderValue::from_static("proto=https"));
    assert!(!client_visible_secure(false, &trusted_addr(), &headers, &cidr_10()));
  }
}
